# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.1
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _perfmon_int
else:
    import _perfmon_int

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


PERF_TYPE_HARDWARE = _perfmon_int.PERF_TYPE_HARDWARE
PERF_TYPE_SOFTWARE = _perfmon_int.PERF_TYPE_SOFTWARE
PERF_TYPE_TRACEPOINT = _perfmon_int.PERF_TYPE_TRACEPOINT
PERF_TYPE_HW_CACHE = _perfmon_int.PERF_TYPE_HW_CACHE
PERF_TYPE_RAW = _perfmon_int.PERF_TYPE_RAW
PERF_TYPE_BREAKPOINT = _perfmon_int.PERF_TYPE_BREAKPOINT
PERF_TYPE_MAX = _perfmon_int.PERF_TYPE_MAX
PERF_COUNT_HW_CPU_CYCLES = _perfmon_int.PERF_COUNT_HW_CPU_CYCLES
PERF_COUNT_HW_INSTRUCTIONS = _perfmon_int.PERF_COUNT_HW_INSTRUCTIONS
PERF_COUNT_HW_CACHE_REFERENCES = _perfmon_int.PERF_COUNT_HW_CACHE_REFERENCES
PERF_COUNT_HW_CACHE_MISSES = _perfmon_int.PERF_COUNT_HW_CACHE_MISSES
PERF_COUNT_HW_BRANCH_INSTRUCTIONS = _perfmon_int.PERF_COUNT_HW_BRANCH_INSTRUCTIONS
PERF_COUNT_HW_BRANCH_MISSES = _perfmon_int.PERF_COUNT_HW_BRANCH_MISSES
PERF_COUNT_HW_BUS_CYCLES = _perfmon_int.PERF_COUNT_HW_BUS_CYCLES
PERF_COUNT_HW_STALLED_CYCLES_FRONTEND = _perfmon_int.PERF_COUNT_HW_STALLED_CYCLES_FRONTEND
PERF_COUNT_HW_STALLED_CYCLES_BACKEND = _perfmon_int.PERF_COUNT_HW_STALLED_CYCLES_BACKEND
PERF_COUNT_HW_REF_CPU_CYCLES = _perfmon_int.PERF_COUNT_HW_REF_CPU_CYCLES
PERF_COUNT_HW_MAX = _perfmon_int.PERF_COUNT_HW_MAX
PERF_COUNT_HW_CACHE_L1D = _perfmon_int.PERF_COUNT_HW_CACHE_L1D
PERF_COUNT_HW_CACHE_L1I = _perfmon_int.PERF_COUNT_HW_CACHE_L1I
PERF_COUNT_HW_CACHE_LL = _perfmon_int.PERF_COUNT_HW_CACHE_LL
PERF_COUNT_HW_CACHE_DTLB = _perfmon_int.PERF_COUNT_HW_CACHE_DTLB
PERF_COUNT_HW_CACHE_ITLB = _perfmon_int.PERF_COUNT_HW_CACHE_ITLB
PERF_COUNT_HW_CACHE_BPU = _perfmon_int.PERF_COUNT_HW_CACHE_BPU
PERF_COUNT_HW_CACHE_NODE = _perfmon_int.PERF_COUNT_HW_CACHE_NODE
PERF_COUNT_HW_CACHE_MAX = _perfmon_int.PERF_COUNT_HW_CACHE_MAX
PERF_COUNT_HW_CACHE_OP_READ = _perfmon_int.PERF_COUNT_HW_CACHE_OP_READ
PERF_COUNT_HW_CACHE_OP_WRITE = _perfmon_int.PERF_COUNT_HW_CACHE_OP_WRITE
PERF_COUNT_HW_CACHE_OP_PREFETCH = _perfmon_int.PERF_COUNT_HW_CACHE_OP_PREFETCH
PERF_COUNT_HW_CACHE_OP_MAX = _perfmon_int.PERF_COUNT_HW_CACHE_OP_MAX
PERF_COUNT_HW_CACHE_RESULT_ACCESS = _perfmon_int.PERF_COUNT_HW_CACHE_RESULT_ACCESS
PERF_COUNT_HW_CACHE_RESULT_MISS = _perfmon_int.PERF_COUNT_HW_CACHE_RESULT_MISS
PERF_COUNT_HW_CACHE_RESULT_MAX = _perfmon_int.PERF_COUNT_HW_CACHE_RESULT_MAX
PERF_COUNT_SW_CPU_CLOCK = _perfmon_int.PERF_COUNT_SW_CPU_CLOCK
PERF_COUNT_SW_TASK_CLOCK = _perfmon_int.PERF_COUNT_SW_TASK_CLOCK
PERF_COUNT_SW_PAGE_FAULTS = _perfmon_int.PERF_COUNT_SW_PAGE_FAULTS
PERF_COUNT_SW_CONTEXT_SWITCHES = _perfmon_int.PERF_COUNT_SW_CONTEXT_SWITCHES
PERF_COUNT_SW_CPU_MIGRATIONS = _perfmon_int.PERF_COUNT_SW_CPU_MIGRATIONS
PERF_COUNT_SW_PAGE_FAULTS_MIN = _perfmon_int.PERF_COUNT_SW_PAGE_FAULTS_MIN
PERF_COUNT_SW_PAGE_FAULTS_MAJ = _perfmon_int.PERF_COUNT_SW_PAGE_FAULTS_MAJ
PERF_COUNT_SW_ALIGNMENT_FAULTS = _perfmon_int.PERF_COUNT_SW_ALIGNMENT_FAULTS
PERF_COUNT_SW_EMULATION_FAULTS = _perfmon_int.PERF_COUNT_SW_EMULATION_FAULTS
PERF_COUNT_SW_DUMMY = _perfmon_int.PERF_COUNT_SW_DUMMY
PERF_COUNT_SW_BPF_OUTPUT = _perfmon_int.PERF_COUNT_SW_BPF_OUTPUT
PERF_COUNT_SW_MAX = _perfmon_int.PERF_COUNT_SW_MAX
PERF_SAMPLE_IP = _perfmon_int.PERF_SAMPLE_IP
PERF_SAMPLE_TID = _perfmon_int.PERF_SAMPLE_TID
PERF_SAMPLE_TIME = _perfmon_int.PERF_SAMPLE_TIME
PERF_SAMPLE_ADDR = _perfmon_int.PERF_SAMPLE_ADDR
PERF_SAMPLE_READ = _perfmon_int.PERF_SAMPLE_READ
PERF_SAMPLE_CALLCHAIN = _perfmon_int.PERF_SAMPLE_CALLCHAIN
PERF_SAMPLE_ID = _perfmon_int.PERF_SAMPLE_ID
PERF_SAMPLE_CPU = _perfmon_int.PERF_SAMPLE_CPU
PERF_SAMPLE_PERIOD = _perfmon_int.PERF_SAMPLE_PERIOD
PERF_SAMPLE_STREAM_ID = _perfmon_int.PERF_SAMPLE_STREAM_ID
PERF_SAMPLE_RAW = _perfmon_int.PERF_SAMPLE_RAW
PERF_SAMPLE_BRANCH_STACK = _perfmon_int.PERF_SAMPLE_BRANCH_STACK
PERF_SAMPLE_REGS_USER = _perfmon_int.PERF_SAMPLE_REGS_USER
PERF_SAMPLE_STACK_USER = _perfmon_int.PERF_SAMPLE_STACK_USER
PERF_SAMPLE_WEIGHT = _perfmon_int.PERF_SAMPLE_WEIGHT
PERF_SAMPLE_DATA_SRC = _perfmon_int.PERF_SAMPLE_DATA_SRC
PERF_SAMPLE_IDENTIFIER = _perfmon_int.PERF_SAMPLE_IDENTIFIER
PERF_SAMPLE_TRANSACTION = _perfmon_int.PERF_SAMPLE_TRANSACTION
PERF_SAMPLE_REGS_INTR = _perfmon_int.PERF_SAMPLE_REGS_INTR
PERF_SAMPLE_PHYS_ADDR = _perfmon_int.PERF_SAMPLE_PHYS_ADDR
PERF_SAMPLE_MAX = _perfmon_int.PERF_SAMPLE_MAX
PERF_TXN_ELISION = _perfmon_int.PERF_TXN_ELISION
PERF_TXN_TRANSACTION = _perfmon_int.PERF_TXN_TRANSACTION
PERF_TXN_SYNC = _perfmon_int.PERF_TXN_SYNC
PERF_TXN_ASYNC = _perfmon_int.PERF_TXN_ASYNC
PERF_TXN_RETRY = _perfmon_int.PERF_TXN_RETRY
PERF_TXN_CONFLICT = _perfmon_int.PERF_TXN_CONFLICT
PERF_TXN_CAPACITY_WRITE = _perfmon_int.PERF_TXN_CAPACITY_WRITE
PERF_TXN_CAPACITY_READ = _perfmon_int.PERF_TXN_CAPACITY_READ
PERF_TXN_MAX = _perfmon_int.PERF_TXN_MAX
PERF_TXN_ABORT_MASK = _perfmon_int.PERF_TXN_ABORT_MASK
PERF_TXN_ABORT_SHIFT = _perfmon_int.PERF_TXN_ABORT_SHIFT
PERF_SAMPLE_BRANCH_USER_SHIFT = _perfmon_int.PERF_SAMPLE_BRANCH_USER_SHIFT
PERF_SAMPLE_BRANCH_KERNEL_SHIFT = _perfmon_int.PERF_SAMPLE_BRANCH_KERNEL_SHIFT
PERF_SAMPLE_BRANCH_HV_SHIFT = _perfmon_int.PERF_SAMPLE_BRANCH_HV_SHIFT
PERF_SAMPLE_BRANCH_ANY_SHIFT = _perfmon_int.PERF_SAMPLE_BRANCH_ANY_SHIFT
PERF_SAMPLE_BRANCH_ANY_CALL_SHIFT = _perfmon_int.PERF_SAMPLE_BRANCH_ANY_CALL_SHIFT
PERF_SAMPLE_BRANCH_ANY_RETURN_SHIFT = _perfmon_int.PERF_SAMPLE_BRANCH_ANY_RETURN_SHIFT
PERF_SAMPLE_BRANCH_IND_CALL_SHIFT = _perfmon_int.PERF_SAMPLE_BRANCH_IND_CALL_SHIFT
PERF_SAMPLE_BRANCH_ABORT_TX_SHIFT = _perfmon_int.PERF_SAMPLE_BRANCH_ABORT_TX_SHIFT
PERF_SAMPLE_BRANCH_IN_TX_SHIFT = _perfmon_int.PERF_SAMPLE_BRANCH_IN_TX_SHIFT
PERF_SAMPLE_BRANCH_NO_TX_SHIFT = _perfmon_int.PERF_SAMPLE_BRANCH_NO_TX_SHIFT
PERF_SAMPLE_BRANCH_COND_SHIFT = _perfmon_int.PERF_SAMPLE_BRANCH_COND_SHIFT
PERF_SAMPLE_BRANCH_CALL_STACK_SHIFT = _perfmon_int.PERF_SAMPLE_BRANCH_CALL_STACK_SHIFT
PERF_SAMPLE_BRANCH_IND_JUMP_SHIFT = _perfmon_int.PERF_SAMPLE_BRANCH_IND_JUMP_SHIFT
PERF_SAMPLE_BRANCH_CALL_SHIFT = _perfmon_int.PERF_SAMPLE_BRANCH_CALL_SHIFT
PERF_SAMPLE_BRANCH_NO_FLAGS_SHIFT = _perfmon_int.PERF_SAMPLE_BRANCH_NO_FLAGS_SHIFT
PERF_SAMPLE_BRANCH_NO_CYCLES_SHIFT = _perfmon_int.PERF_SAMPLE_BRANCH_NO_CYCLES_SHIFT
PERF_SAMPLE_BRANCH_TYPE_SAVE_SHIFT = _perfmon_int.PERF_SAMPLE_BRANCH_TYPE_SAVE_SHIFT
PERF_SAMPLE_BRANCH_MAX_SHIFT = _perfmon_int.PERF_SAMPLE_BRANCH_MAX_SHIFT
PERF_SAMPLE_BRANCH_USER = _perfmon_int.PERF_SAMPLE_BRANCH_USER
PERF_SAMPLE_BRANCH_KERNEL = _perfmon_int.PERF_SAMPLE_BRANCH_KERNEL
PERF_SAMPLE_BRANCH_HV = _perfmon_int.PERF_SAMPLE_BRANCH_HV
PERF_SAMPLE_BRANCH_ANY = _perfmon_int.PERF_SAMPLE_BRANCH_ANY
PERF_SAMPLE_BRANCH_ANY_CALL = _perfmon_int.PERF_SAMPLE_BRANCH_ANY_CALL
PERF_SAMPLE_BRANCH_ANY_RETURN = _perfmon_int.PERF_SAMPLE_BRANCH_ANY_RETURN
PERF_SAMPLE_BRANCH_IND_CALL = _perfmon_int.PERF_SAMPLE_BRANCH_IND_CALL
PERF_SAMPLE_BRANCH_ABORT_TX = _perfmon_int.PERF_SAMPLE_BRANCH_ABORT_TX
PERF_SAMPLE_BRANCH_IN_TX = _perfmon_int.PERF_SAMPLE_BRANCH_IN_TX
PERF_SAMPLE_BRANCH_NO_TX = _perfmon_int.PERF_SAMPLE_BRANCH_NO_TX
PERF_SAMPLE_BRANCH_COND = _perfmon_int.PERF_SAMPLE_BRANCH_COND
PERF_SAMPLE_BRANCH_CALL_STACK = _perfmon_int.PERF_SAMPLE_BRANCH_CALL_STACK
PERF_SAMPLE_BRANCH_IND_JUMP = _perfmon_int.PERF_SAMPLE_BRANCH_IND_JUMP
PERF_SAMPLE_BRANCH_CALL = _perfmon_int.PERF_SAMPLE_BRANCH_CALL
PERF_SAMPLE_BRANCH_NO_FLAGS = _perfmon_int.PERF_SAMPLE_BRANCH_NO_FLAGS
PERF_SAMPLE_BRANCH_NO_CYCLES = _perfmon_int.PERF_SAMPLE_BRANCH_NO_CYCLES
PERF_SAMPLE_BRANCH_TYPE_SAVE = _perfmon_int.PERF_SAMPLE_BRANCH_TYPE_SAVE
PERF_SAMPLE_BRANCH_MAX = _perfmon_int.PERF_SAMPLE_BRANCH_MAX
PERF_SAMPLE_REGS_ABI_NONE = _perfmon_int.PERF_SAMPLE_REGS_ABI_NONE
PERF_SAMPLE_REGS_ABI_32 = _perfmon_int.PERF_SAMPLE_REGS_ABI_32
PERF_SAMPLE_REGS_ABI_64 = _perfmon_int.PERF_SAMPLE_REGS_ABI_64
PERF_FORMAT_TOTAL_TIME_ENABLED = _perfmon_int.PERF_FORMAT_TOTAL_TIME_ENABLED
PERF_FORMAT_TOTAL_TIME_RUNNING = _perfmon_int.PERF_FORMAT_TOTAL_TIME_RUNNING
PERF_FORMAT_ID = _perfmon_int.PERF_FORMAT_ID
PERF_FORMAT_GROUP = _perfmon_int.PERF_FORMAT_GROUP
PERF_FORMAT_MAX = _perfmon_int.PERF_FORMAT_MAX
PERF_ATTR_SIZE_VER0 = _perfmon_int.PERF_ATTR_SIZE_VER0
PERF_ATTR_SIZE_VER1 = _perfmon_int.PERF_ATTR_SIZE_VER1
PERF_ATTR_SIZE_VER2 = _perfmon_int.PERF_ATTR_SIZE_VER2
PERF_ATTR_SIZE_VER3 = _perfmon_int.PERF_ATTR_SIZE_VER3
PERF_ATTR_SIZE_VER4 = _perfmon_int.PERF_ATTR_SIZE_VER4
PERF_ATTR_SIZE_VER5 = _perfmon_int.PERF_ATTR_SIZE_VER5
class perf_event_attr_t(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    type = property(_perfmon_int.perf_event_attr_t_type_get, _perfmon_int.perf_event_attr_t_type_set)
    size = property(_perfmon_int.perf_event_attr_t_size_get, _perfmon_int.perf_event_attr_t_size_set)
    config = property(_perfmon_int.perf_event_attr_t_config_get, _perfmon_int.perf_event_attr_t_config_set)
    sample = property(_perfmon_int.perf_event_attr_t_sample_get)
    sample_type = property(_perfmon_int.perf_event_attr_t_sample_type_get, _perfmon_int.perf_event_attr_t_sample_type_set)
    read_format = property(_perfmon_int.perf_event_attr_t_read_format_get, _perfmon_int.perf_event_attr_t_read_format_set)
    disabled = property(_perfmon_int.perf_event_attr_t_disabled_get, _perfmon_int.perf_event_attr_t_disabled_set)
    inherit = property(_perfmon_int.perf_event_attr_t_inherit_get, _perfmon_int.perf_event_attr_t_inherit_set)
    pinned = property(_perfmon_int.perf_event_attr_t_pinned_get, _perfmon_int.perf_event_attr_t_pinned_set)
    exclusive = property(_perfmon_int.perf_event_attr_t_exclusive_get, _perfmon_int.perf_event_attr_t_exclusive_set)
    exclude_user = property(_perfmon_int.perf_event_attr_t_exclude_user_get, _perfmon_int.perf_event_attr_t_exclude_user_set)
    exclude_kernel = property(_perfmon_int.perf_event_attr_t_exclude_kernel_get, _perfmon_int.perf_event_attr_t_exclude_kernel_set)
    exclude_hv = property(_perfmon_int.perf_event_attr_t_exclude_hv_get, _perfmon_int.perf_event_attr_t_exclude_hv_set)
    exclude_idle = property(_perfmon_int.perf_event_attr_t_exclude_idle_get, _perfmon_int.perf_event_attr_t_exclude_idle_set)
    mmap = property(_perfmon_int.perf_event_attr_t_mmap_get, _perfmon_int.perf_event_attr_t_mmap_set)
    comm = property(_perfmon_int.perf_event_attr_t_comm_get, _perfmon_int.perf_event_attr_t_comm_set)
    freq = property(_perfmon_int.perf_event_attr_t_freq_get, _perfmon_int.perf_event_attr_t_freq_set)
    inherit_stat = property(_perfmon_int.perf_event_attr_t_inherit_stat_get, _perfmon_int.perf_event_attr_t_inherit_stat_set)
    enable_on_exec = property(_perfmon_int.perf_event_attr_t_enable_on_exec_get, _perfmon_int.perf_event_attr_t_enable_on_exec_set)
    task = property(_perfmon_int.perf_event_attr_t_task_get, _perfmon_int.perf_event_attr_t_task_set)
    watermark = property(_perfmon_int.perf_event_attr_t_watermark_get, _perfmon_int.perf_event_attr_t_watermark_set)
    precise_ip = property(_perfmon_int.perf_event_attr_t_precise_ip_get, _perfmon_int.perf_event_attr_t_precise_ip_set)
    mmap_data = property(_perfmon_int.perf_event_attr_t_mmap_data_get, _perfmon_int.perf_event_attr_t_mmap_data_set)
    sample_id_all = property(_perfmon_int.perf_event_attr_t_sample_id_all_get, _perfmon_int.perf_event_attr_t_sample_id_all_set)
    exclude_host = property(_perfmon_int.perf_event_attr_t_exclude_host_get, _perfmon_int.perf_event_attr_t_exclude_host_set)
    exclude_guest = property(_perfmon_int.perf_event_attr_t_exclude_guest_get, _perfmon_int.perf_event_attr_t_exclude_guest_set)
    exclude_callchain_kernel = property(_perfmon_int.perf_event_attr_t_exclude_callchain_kernel_get, _perfmon_int.perf_event_attr_t_exclude_callchain_kernel_set)
    exclude_callchain_user = property(_perfmon_int.perf_event_attr_t_exclude_callchain_user_get, _perfmon_int.perf_event_attr_t_exclude_callchain_user_set)
    mmap2 = property(_perfmon_int.perf_event_attr_t_mmap2_get, _perfmon_int.perf_event_attr_t_mmap2_set)
    comm_exec = property(_perfmon_int.perf_event_attr_t_comm_exec_get, _perfmon_int.perf_event_attr_t_comm_exec_set)
    use_clockid = property(_perfmon_int.perf_event_attr_t_use_clockid_get, _perfmon_int.perf_event_attr_t_use_clockid_set)
    context_switch = property(_perfmon_int.perf_event_attr_t_context_switch_get, _perfmon_int.perf_event_attr_t_context_switch_set)
    write_backward = property(_perfmon_int.perf_event_attr_t_write_backward_get, _perfmon_int.perf_event_attr_t_write_backward_set)
    namespaces = property(_perfmon_int.perf_event_attr_t_namespaces_get, _perfmon_int.perf_event_attr_t_namespaces_set)
    __reserved_1 = property(_perfmon_int.perf_event_attr_t___reserved_1_get, _perfmon_int.perf_event_attr_t___reserved_1_set)
    wakeup = property(_perfmon_int.perf_event_attr_t_wakeup_get)
    bp_type = property(_perfmon_int.perf_event_attr_t_bp_type_get, _perfmon_int.perf_event_attr_t_bp_type_set)
    bpa = property(_perfmon_int.perf_event_attr_t_bpa_get)
    bpb = property(_perfmon_int.perf_event_attr_t_bpb_get)
    branch_sample_type = property(_perfmon_int.perf_event_attr_t_branch_sample_type_get, _perfmon_int.perf_event_attr_t_branch_sample_type_set)
    sample_regs_user = property(_perfmon_int.perf_event_attr_t_sample_regs_user_get, _perfmon_int.perf_event_attr_t_sample_regs_user_set)
    sample_stack_user = property(_perfmon_int.perf_event_attr_t_sample_stack_user_get, _perfmon_int.perf_event_attr_t_sample_stack_user_set)
    clockid = property(_perfmon_int.perf_event_attr_t_clockid_get, _perfmon_int.perf_event_attr_t_clockid_set)
    sample_regs_intr = property(_perfmon_int.perf_event_attr_t_sample_regs_intr_get, _perfmon_int.perf_event_attr_t_sample_regs_intr_set)
    aux_watermark = property(_perfmon_int.perf_event_attr_t_aux_watermark_get, _perfmon_int.perf_event_attr_t_aux_watermark_set)
    __reserved_2 = property(_perfmon_int.perf_event_attr_t___reserved_2_get, _perfmon_int.perf_event_attr_t___reserved_2_set)
    __swig_destroy__ = _perfmon_int.delete_perf_event_attr_t

    def __init__(self):
        _perfmon_int.perf_event_attr_t_swiginit(self, _perfmon_int.new_perf_event_attr_t())

# Register perf_event_attr_t in _perfmon_int:
_perfmon_int.perf_event_attr_t_swigregister(perf_event_attr_t)

class perf_event_attr_bpb(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    bp_len = property(_perfmon_int.perf_event_attr_bpb_bp_len_get, _perfmon_int.perf_event_attr_bpb_bp_len_set)
    config2 = property(_perfmon_int.perf_event_attr_bpb_config2_get, _perfmon_int.perf_event_attr_bpb_config2_set)

    def __init__(self):
        _perfmon_int.perf_event_attr_bpb_swiginit(self, _perfmon_int.new_perf_event_attr_bpb())
    __swig_destroy__ = _perfmon_int.delete_perf_event_attr_bpb

# Register perf_event_attr_bpb in _perfmon_int:
_perfmon_int.perf_event_attr_bpb_swigregister(perf_event_attr_bpb)

class perf_event_attr_bpa(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    bp_addr = property(_perfmon_int.perf_event_attr_bpa_bp_addr_get, _perfmon_int.perf_event_attr_bpa_bp_addr_set)
    config1 = property(_perfmon_int.perf_event_attr_bpa_config1_get, _perfmon_int.perf_event_attr_bpa_config1_set)

    def __init__(self):
        _perfmon_int.perf_event_attr_bpa_swiginit(self, _perfmon_int.new_perf_event_attr_bpa())
    __swig_destroy__ = _perfmon_int.delete_perf_event_attr_bpa

# Register perf_event_attr_bpa in _perfmon_int:
_perfmon_int.perf_event_attr_bpa_swigregister(perf_event_attr_bpa)

class perf_event_attr_wakeup(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    wakeup_events = property(_perfmon_int.perf_event_attr_wakeup_wakeup_events_get, _perfmon_int.perf_event_attr_wakeup_wakeup_events_set)
    wakeup_watermark = property(_perfmon_int.perf_event_attr_wakeup_wakeup_watermark_get, _perfmon_int.perf_event_attr_wakeup_wakeup_watermark_set)

    def __init__(self):
        _perfmon_int.perf_event_attr_wakeup_swiginit(self, _perfmon_int.new_perf_event_attr_wakeup())
    __swig_destroy__ = _perfmon_int.delete_perf_event_attr_wakeup

# Register perf_event_attr_wakeup in _perfmon_int:
_perfmon_int.perf_event_attr_wakeup_swigregister(perf_event_attr_wakeup)

class perf_event_attr_sample(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    sample_period = property(_perfmon_int.perf_event_attr_sample_sample_period_get, _perfmon_int.perf_event_attr_sample_sample_period_set)
    sample_freq = property(_perfmon_int.perf_event_attr_sample_sample_freq_get, _perfmon_int.perf_event_attr_sample_sample_freq_set)

    def __init__(self):
        _perfmon_int.perf_event_attr_sample_swiginit(self, _perfmon_int.new_perf_event_attr_sample())
    __swig_destroy__ = _perfmon_int.delete_perf_event_attr_sample

# Register perf_event_attr_sample in _perfmon_int:
_perfmon_int.perf_event_attr_sample_swigregister(perf_event_attr_sample)

class perf_branch_entry(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    _from = property(_perfmon_int.perf_branch_entry__from_get, _perfmon_int.perf_branch_entry__from_set)
    to = property(_perfmon_int.perf_branch_entry_to_get, _perfmon_int.perf_branch_entry_to_set)
    mispred = property(_perfmon_int.perf_branch_entry_mispred_get, _perfmon_int.perf_branch_entry_mispred_set)
    predicted = property(_perfmon_int.perf_branch_entry_predicted_get, _perfmon_int.perf_branch_entry_predicted_set)
    in_tx = property(_perfmon_int.perf_branch_entry_in_tx_get, _perfmon_int.perf_branch_entry_in_tx_set)
    abort = property(_perfmon_int.perf_branch_entry_abort_get, _perfmon_int.perf_branch_entry_abort_set)
    cycles = property(_perfmon_int.perf_branch_entry_cycles_get, _perfmon_int.perf_branch_entry_cycles_set)
    type = property(_perfmon_int.perf_branch_entry_type_get, _perfmon_int.perf_branch_entry_type_set)
    reserved = property(_perfmon_int.perf_branch_entry_reserved_get, _perfmon_int.perf_branch_entry_reserved_set)

    def __init__(self):
        _perfmon_int.perf_branch_entry_swiginit(self, _perfmon_int.new_perf_branch_entry())
    __swig_destroy__ = _perfmon_int.delete_perf_branch_entry

# Register perf_branch_entry in _perfmon_int:
_perfmon_int.perf_branch_entry_swigregister(perf_branch_entry)

class perf_branch_stack(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    nr = property(_perfmon_int.perf_branch_stack_nr_get, _perfmon_int.perf_branch_stack_nr_set)
    entries = property(_perfmon_int.perf_branch_stack_entries_get, _perfmon_int.perf_branch_stack_entries_set)

    def __init__(self):
        _perfmon_int.perf_branch_stack_swiginit(self, _perfmon_int.new_perf_branch_stack())
    __swig_destroy__ = _perfmon_int.delete_perf_branch_stack

# Register perf_branch_stack in _perfmon_int:
_perfmon_int.perf_branch_stack_swigregister(perf_branch_stack)

PERF_IOC_FLAG_GROUP = _perfmon_int.PERF_IOC_FLAG_GROUP
class perf_event_mmap_page(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    version = property(_perfmon_int.perf_event_mmap_page_version_get, _perfmon_int.perf_event_mmap_page_version_set)
    compat_version = property(_perfmon_int.perf_event_mmap_page_compat_version_get, _perfmon_int.perf_event_mmap_page_compat_version_set)
    lock = property(_perfmon_int.perf_event_mmap_page_lock_get, _perfmon_int.perf_event_mmap_page_lock_set)
    index = property(_perfmon_int.perf_event_mmap_page_index_get, _perfmon_int.perf_event_mmap_page_index_set)
    offset = property(_perfmon_int.perf_event_mmap_page_offset_get, _perfmon_int.perf_event_mmap_page_offset_set)
    time_enabled = property(_perfmon_int.perf_event_mmap_page_time_enabled_get, _perfmon_int.perf_event_mmap_page_time_enabled_set)
    time_running = property(_perfmon_int.perf_event_mmap_page_time_running_get, _perfmon_int.perf_event_mmap_page_time_running_set)
    rdmap_cap_u = property(_perfmon_int.perf_event_mmap_page_rdmap_cap_u_get)
    pmc_width = property(_perfmon_int.perf_event_mmap_page_pmc_width_get, _perfmon_int.perf_event_mmap_page_pmc_width_set)
    time_shift = property(_perfmon_int.perf_event_mmap_page_time_shift_get, _perfmon_int.perf_event_mmap_page_time_shift_set)
    time_mult = property(_perfmon_int.perf_event_mmap_page_time_mult_get, _perfmon_int.perf_event_mmap_page_time_mult_set)
    time_offset = property(_perfmon_int.perf_event_mmap_page_time_offset_get, _perfmon_int.perf_event_mmap_page_time_offset_set)
    time_zero = property(_perfmon_int.perf_event_mmap_page_time_zero_get, _perfmon_int.perf_event_mmap_page_time_zero_set)
    size = property(_perfmon_int.perf_event_mmap_page_size_get, _perfmon_int.perf_event_mmap_page_size_set)
    __reserved = property(_perfmon_int.perf_event_mmap_page___reserved_get, _perfmon_int.perf_event_mmap_page___reserved_set)
    data_head = property(_perfmon_int.perf_event_mmap_page_data_head_get, _perfmon_int.perf_event_mmap_page_data_head_set)
    data_tail = property(_perfmon_int.perf_event_mmap_page_data_tail_get, _perfmon_int.perf_event_mmap_page_data_tail_set)
    data_offset = property(_perfmon_int.perf_event_mmap_page_data_offset_get, _perfmon_int.perf_event_mmap_page_data_offset_set)
    data_size = property(_perfmon_int.perf_event_mmap_page_data_size_get, _perfmon_int.perf_event_mmap_page_data_size_set)
    aux_head = property(_perfmon_int.perf_event_mmap_page_aux_head_get, _perfmon_int.perf_event_mmap_page_aux_head_set)
    aux_tail = property(_perfmon_int.perf_event_mmap_page_aux_tail_get, _perfmon_int.perf_event_mmap_page_aux_tail_set)
    aux_offset = property(_perfmon_int.perf_event_mmap_page_aux_offset_get, _perfmon_int.perf_event_mmap_page_aux_offset_set)
    aux_size = property(_perfmon_int.perf_event_mmap_page_aux_size_get, _perfmon_int.perf_event_mmap_page_aux_size_set)

    def __init__(self):
        _perfmon_int.perf_event_mmap_page_swiginit(self, _perfmon_int.new_perf_event_mmap_page())
    __swig_destroy__ = _perfmon_int.delete_perf_event_mmap_page

# Register perf_event_mmap_page in _perfmon_int:
_perfmon_int.perf_event_mmap_page_swigregister(perf_event_mmap_page)

class perf_event_mmap_page_rdmap_cap_u(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    capabilities = property(_perfmon_int.perf_event_mmap_page_rdmap_cap_u_capabilities_get, _perfmon_int.perf_event_mmap_page_rdmap_cap_u_capabilities_set)
    rdmap_cap_s = property(_perfmon_int.perf_event_mmap_page_rdmap_cap_u_rdmap_cap_s_get)

    def __init__(self):
        _perfmon_int.perf_event_mmap_page_rdmap_cap_u_swiginit(self, _perfmon_int.new_perf_event_mmap_page_rdmap_cap_u())
    __swig_destroy__ = _perfmon_int.delete_perf_event_mmap_page_rdmap_cap_u

# Register perf_event_mmap_page_rdmap_cap_u in _perfmon_int:
_perfmon_int.perf_event_mmap_page_rdmap_cap_u_swigregister(perf_event_mmap_page_rdmap_cap_u)

class perf_event_mmap_page_rdmap_cap_u_rdmap_cap_s(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    cap_bit0 = property(_perfmon_int.perf_event_mmap_page_rdmap_cap_u_rdmap_cap_s_cap_bit0_get, _perfmon_int.perf_event_mmap_page_rdmap_cap_u_rdmap_cap_s_cap_bit0_set)
    cap_bit0_is_deprecated = property(_perfmon_int.perf_event_mmap_page_rdmap_cap_u_rdmap_cap_s_cap_bit0_is_deprecated_get, _perfmon_int.perf_event_mmap_page_rdmap_cap_u_rdmap_cap_s_cap_bit0_is_deprecated_set)
    cap_usr_rdpmc = property(_perfmon_int.perf_event_mmap_page_rdmap_cap_u_rdmap_cap_s_cap_usr_rdpmc_get, _perfmon_int.perf_event_mmap_page_rdmap_cap_u_rdmap_cap_s_cap_usr_rdpmc_set)
    cap_user_time = property(_perfmon_int.perf_event_mmap_page_rdmap_cap_u_rdmap_cap_s_cap_user_time_get, _perfmon_int.perf_event_mmap_page_rdmap_cap_u_rdmap_cap_s_cap_user_time_set)
    cap_user_time_zero = property(_perfmon_int.perf_event_mmap_page_rdmap_cap_u_rdmap_cap_s_cap_user_time_zero_get, _perfmon_int.perf_event_mmap_page_rdmap_cap_u_rdmap_cap_s_cap_user_time_zero_set)
    cap_____res = property(_perfmon_int.perf_event_mmap_page_rdmap_cap_u_rdmap_cap_s_cap_____res_get, _perfmon_int.perf_event_mmap_page_rdmap_cap_u_rdmap_cap_s_cap_____res_set)

    def __init__(self):
        _perfmon_int.perf_event_mmap_page_rdmap_cap_u_rdmap_cap_s_swiginit(self, _perfmon_int.new_perf_event_mmap_page_rdmap_cap_u_rdmap_cap_s())
    __swig_destroy__ = _perfmon_int.delete_perf_event_mmap_page_rdmap_cap_u_rdmap_cap_s

# Register perf_event_mmap_page_rdmap_cap_u_rdmap_cap_s in _perfmon_int:
_perfmon_int.perf_event_mmap_page_rdmap_cap_u_rdmap_cap_s_swigregister(perf_event_mmap_page_rdmap_cap_u_rdmap_cap_s)

class perf_event_header(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    type = property(_perfmon_int.perf_event_header_type_get, _perfmon_int.perf_event_header_type_set)
    misc = property(_perfmon_int.perf_event_header_misc_get, _perfmon_int.perf_event_header_misc_set)
    size = property(_perfmon_int.perf_event_header_size_get, _perfmon_int.perf_event_header_size_set)

    def __init__(self):
        _perfmon_int.perf_event_header_swiginit(self, _perfmon_int.new_perf_event_header())
    __swig_destroy__ = _perfmon_int.delete_perf_event_header

# Register perf_event_header in _perfmon_int:
_perfmon_int.perf_event_header_swigregister(perf_event_header)

PERF_EVENT_MISC_CPUMODE_MASK = _perfmon_int.PERF_EVENT_MISC_CPUMODE_MASK
PERF_EVENT_MISC_CPUMODE_UNKNOWN = _perfmon_int.PERF_EVENT_MISC_CPUMODE_UNKNOWN
PERF_EVENT_MISC_KERNEL = _perfmon_int.PERF_EVENT_MISC_KERNEL
PERF_EVENT_MISC_USER = _perfmon_int.PERF_EVENT_MISC_USER
PERF_EVENT_MISC_HYPERVISOR = _perfmon_int.PERF_EVENT_MISC_HYPERVISOR
PERF_RECORD_MISC_GUEST_KERNEL = _perfmon_int.PERF_RECORD_MISC_GUEST_KERNEL
PERF_RECORD_MISC_GUEST_USER = _perfmon_int.PERF_RECORD_MISC_GUEST_USER
PERF_RECORD_MISC_PROC_MAP_PARSE_TIMEOUT = _perfmon_int.PERF_RECORD_MISC_PROC_MAP_PARSE_TIMEOUT
PERF_RECORD_MISC_MMAP_DATA = _perfmon_int.PERF_RECORD_MISC_MMAP_DATA
PERF_RECORD_MISC_COMM_EXEC = _perfmon_int.PERF_RECORD_MISC_COMM_EXEC
PERF_RECORD_MISC_EXACT = _perfmon_int.PERF_RECORD_MISC_EXACT
PERF_RECORD_MISC_EXACT_IP = _perfmon_int.PERF_RECORD_MISC_EXACT_IP
PERF_RECORD_MISC_EXT_RESERVED = _perfmon_int.PERF_RECORD_MISC_EXT_RESERVED
PERF_RECORD_MMAP = _perfmon_int.PERF_RECORD_MMAP
PERF_RECORD_LOST = _perfmon_int.PERF_RECORD_LOST
PERF_RECORD_COMM = _perfmon_int.PERF_RECORD_COMM
PERF_RECORD_EXIT = _perfmon_int.PERF_RECORD_EXIT
PERF_RECORD_THROTTLE = _perfmon_int.PERF_RECORD_THROTTLE
PERF_RECORD_UNTHROTTLE = _perfmon_int.PERF_RECORD_UNTHROTTLE
PERF_RECORD_FORK = _perfmon_int.PERF_RECORD_FORK
PERF_RECORD_READ = _perfmon_int.PERF_RECORD_READ
PERF_RECORD_SAMPLE = _perfmon_int.PERF_RECORD_SAMPLE
PERF_RECORD_MMAP2 = _perfmon_int.PERF_RECORD_MMAP2
PERF_RECORD_AUX = _perfmon_int.PERF_RECORD_AUX
PERF_RECORD_ITRACE_START = _perfmon_int.PERF_RECORD_ITRACE_START
PERF_RECORD_LOST_SAMPLES = _perfmon_int.PERF_RECORD_LOST_SAMPLES
PERF_RECORD_SWITCH = _perfmon_int.PERF_RECORD_SWITCH
PERF_RECORD_SWITCH_CPU_WIDE = _perfmon_int.PERF_RECORD_SWITCH_CPU_WIDE
PERF_RECORD_NAMESPACES = _perfmon_int.PERF_RECORD_NAMESPACES
PERF_RECORD_MAX = _perfmon_int.PERF_RECORD_MAX
PERF_CONTEXT_HV = _perfmon_int.PERF_CONTEXT_HV
PERF_CONTEXT_KERNEL = _perfmon_int.PERF_CONTEXT_KERNEL
PERF_CONTEXT_USER = _perfmon_int.PERF_CONTEXT_USER
PERF_CONTEXT_GUEST = _perfmon_int.PERF_CONTEXT_GUEST
PERF_CONTEXT_GUEST_KERNEL = _perfmon_int.PERF_CONTEXT_GUEST_KERNEL
PERF_CONTEXT_GUEST_USER = _perfmon_int.PERF_CONTEXT_GUEST_USER
PERF_CONTEXT_MAX = _perfmon_int.PERF_CONTEXT_MAX
PERF_AUX_FLAG_TRUNCATED = _perfmon_int.PERF_AUX_FLAG_TRUNCATED
PERF_AUX_FLAG_OVERWRITE = _perfmon_int.PERF_AUX_FLAG_OVERWRITE
PERF_FLAG_FD_NO_GROUP = _perfmon_int.PERF_FLAG_FD_NO_GROUP
PERF_FLAG_FD_OUTPUT = _perfmon_int.PERF_FLAG_FD_OUTPUT
PERF_FLAG_PID_CGROUP = _perfmon_int.PERF_FLAG_PID_CGROUP
PERF_FLAG_FD_CLOEXEC = _perfmon_int.PERF_FLAG_FD_CLOEXEC

def perf_event_open(hw_event_uptr, pid, cpu, group_fd, flags):
    return _perfmon_int.perf_event_open(hw_event_uptr, pid, cpu, group_fd, flags)
PR_TASK_PERF_EVENTS_ENABLE = _perfmon_int.PR_TASK_PERF_EVENTS_ENABLE
PR_TASK_PERF_EVENTS_DISABLE = _perfmon_int.PR_TASK_PERF_EVENTS_DISABLE
class perf_mem_data_src(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    val = property(_perfmon_int.perf_mem_data_src_val_get, _perfmon_int.perf_mem_data_src_val_set)
    mem_op = property(_perfmon_int.perf_mem_data_src_mem_op_get, _perfmon_int.perf_mem_data_src_mem_op_set)
    mem_lvl = property(_perfmon_int.perf_mem_data_src_mem_lvl_get, _perfmon_int.perf_mem_data_src_mem_lvl_set)
    mem_snoop = property(_perfmon_int.perf_mem_data_src_mem_snoop_get, _perfmon_int.perf_mem_data_src_mem_snoop_set)
    mem_lock = property(_perfmon_int.perf_mem_data_src_mem_lock_get, _perfmon_int.perf_mem_data_src_mem_lock_set)
    mem_dtlb = property(_perfmon_int.perf_mem_data_src_mem_dtlb_get, _perfmon_int.perf_mem_data_src_mem_dtlb_set)
    mem_rsvd = property(_perfmon_int.perf_mem_data_src_mem_rsvd_get, _perfmon_int.perf_mem_data_src_mem_rsvd_set)

    def __init__(self):
        _perfmon_int.perf_mem_data_src_swiginit(self, _perfmon_int.new_perf_mem_data_src())
    __swig_destroy__ = _perfmon_int.delete_perf_mem_data_src

# Register perf_mem_data_src in _perfmon_int:
_perfmon_int.perf_mem_data_src_swigregister(perf_mem_data_src)

PERF_MEM_OP_NA = _perfmon_int.PERF_MEM_OP_NA
PERF_MEM_OP_LOAD = _perfmon_int.PERF_MEM_OP_LOAD
PERF_MEM_OP_STORE = _perfmon_int.PERF_MEM_OP_STORE
PERF_MEM_OP_PFETCH = _perfmon_int.PERF_MEM_OP_PFETCH
PERF_MEM_OP_EXEC = _perfmon_int.PERF_MEM_OP_EXEC
PERF_MEM_OP_SHIFT = _perfmon_int.PERF_MEM_OP_SHIFT
PERF_MEM_LVL_NA = _perfmon_int.PERF_MEM_LVL_NA
PERF_MEM_LVL_HIT = _perfmon_int.PERF_MEM_LVL_HIT
PERF_MEM_LVL_MISS = _perfmon_int.PERF_MEM_LVL_MISS
PERF_MEM_LVL_L1 = _perfmon_int.PERF_MEM_LVL_L1
PERF_MEM_LVL_LFB = _perfmon_int.PERF_MEM_LVL_LFB
PERF_MEM_LVL_L2 = _perfmon_int.PERF_MEM_LVL_L2
PERF_MEM_LVL_L3 = _perfmon_int.PERF_MEM_LVL_L3
PERF_MEM_LVL_LOC_RAM = _perfmon_int.PERF_MEM_LVL_LOC_RAM
PERF_MEM_LVL_REM_RAM1 = _perfmon_int.PERF_MEM_LVL_REM_RAM1
PERF_MEM_LVL_REM_RAM2 = _perfmon_int.PERF_MEM_LVL_REM_RAM2
PERF_MEM_LVL_REM_CCE1 = _perfmon_int.PERF_MEM_LVL_REM_CCE1
PERF_MEM_LVL_REM_CCE2 = _perfmon_int.PERF_MEM_LVL_REM_CCE2
PERF_MEM_LVL_IO = _perfmon_int.PERF_MEM_LVL_IO
PERF_MEM_LVL_UNC = _perfmon_int.PERF_MEM_LVL_UNC
PERF_MEM_LVL_SHIFT = _perfmon_int.PERF_MEM_LVL_SHIFT
PERF_MEM_REMOTE_REMOTE = _perfmon_int.PERF_MEM_REMOTE_REMOTE
PERF_MEM_REMOTE_SHIFT = _perfmon_int.PERF_MEM_REMOTE_SHIFT
PERF_MEM_SNOOP_NA = _perfmon_int.PERF_MEM_SNOOP_NA
PERF_MEM_SNOOP_NONE = _perfmon_int.PERF_MEM_SNOOP_NONE
PERF_MEM_SNOOP_HIT = _perfmon_int.PERF_MEM_SNOOP_HIT
PERF_MEM_SNOOP_MISS = _perfmon_int.PERF_MEM_SNOOP_MISS
PERF_MEM_SNOOP_HITM = _perfmon_int.PERF_MEM_SNOOP_HITM
PERF_MEM_SNOOP_SHIFT = _perfmon_int.PERF_MEM_SNOOP_SHIFT
PERF_MEM_SNOOPX_FWD = _perfmon_int.PERF_MEM_SNOOPX_FWD
PERF_MEM_SNOOPX_SHIFT = _perfmon_int.PERF_MEM_SNOOPX_SHIFT
PERF_MEM_LOCK_NA = _perfmon_int.PERF_MEM_LOCK_NA
PERF_MEM_LOCK_LOCKED = _perfmon_int.PERF_MEM_LOCK_LOCKED
PERF_MEM_LOCK_SHIFT = _perfmon_int.PERF_MEM_LOCK_SHIFT
PERF_MEM_TLB_NA = _perfmon_int.PERF_MEM_TLB_NA
PERF_MEM_TLB_HIT = _perfmon_int.PERF_MEM_TLB_HIT
PERF_MEM_TLB_MISS = _perfmon_int.PERF_MEM_TLB_MISS
PERF_MEM_TLB_L1 = _perfmon_int.PERF_MEM_TLB_L1
PERF_MEM_TLB_L2 = _perfmon_int.PERF_MEM_TLB_L2
PERF_MEM_TLB_WK = _perfmon_int.PERF_MEM_TLB_WK
PERF_MEM_TLB_OS = _perfmon_int.PERF_MEM_TLB_OS
PERF_MEM_TLB_SHIFT = _perfmon_int.PERF_MEM_TLB_SHIFT
LIBPFM_VERSION = _perfmon_int.LIBPFM_VERSION
LIBPFM_ABI_VERSION = _perfmon_int.LIBPFM_ABI_VERSION
PFM_PLM0 = _perfmon_int.PFM_PLM0
PFM_PLM1 = _perfmon_int.PFM_PLM1
PFM_PLM2 = _perfmon_int.PFM_PLM2
PFM_PLM3 = _perfmon_int.PFM_PLM3
PFM_PLMH = _perfmon_int.PFM_PLMH
PFM_PMU_NONE = _perfmon_int.PFM_PMU_NONE
PFM_PMU_GEN_IA64 = _perfmon_int.PFM_PMU_GEN_IA64
PFM_PMU_ITANIUM = _perfmon_int.PFM_PMU_ITANIUM
PFM_PMU_ITANIUM2 = _perfmon_int.PFM_PMU_ITANIUM2
PFM_PMU_MONTECITO = _perfmon_int.PFM_PMU_MONTECITO
PFM_PMU_AMD64 = _perfmon_int.PFM_PMU_AMD64
PFM_PMU_I386_P6 = _perfmon_int.PFM_PMU_I386_P6
PFM_PMU_INTEL_NETBURST = _perfmon_int.PFM_PMU_INTEL_NETBURST
PFM_PMU_INTEL_NETBURST_P = _perfmon_int.PFM_PMU_INTEL_NETBURST_P
PFM_PMU_COREDUO = _perfmon_int.PFM_PMU_COREDUO
PFM_PMU_I386_PM = _perfmon_int.PFM_PMU_I386_PM
PFM_PMU_INTEL_CORE = _perfmon_int.PFM_PMU_INTEL_CORE
PFM_PMU_INTEL_PPRO = _perfmon_int.PFM_PMU_INTEL_PPRO
PFM_PMU_INTEL_PII = _perfmon_int.PFM_PMU_INTEL_PII
PFM_PMU_INTEL_ATOM = _perfmon_int.PFM_PMU_INTEL_ATOM
PFM_PMU_INTEL_NHM = _perfmon_int.PFM_PMU_INTEL_NHM
PFM_PMU_INTEL_NHM_EX = _perfmon_int.PFM_PMU_INTEL_NHM_EX
PFM_PMU_INTEL_NHM_UNC = _perfmon_int.PFM_PMU_INTEL_NHM_UNC
PFM_PMU_INTEL_X86_ARCH = _perfmon_int.PFM_PMU_INTEL_X86_ARCH
PFM_PMU_MIPS_20KC = _perfmon_int.PFM_PMU_MIPS_20KC
PFM_PMU_MIPS_24K = _perfmon_int.PFM_PMU_MIPS_24K
PFM_PMU_MIPS_25KF = _perfmon_int.PFM_PMU_MIPS_25KF
PFM_PMU_MIPS_34K = _perfmon_int.PFM_PMU_MIPS_34K
PFM_PMU_MIPS_5KC = _perfmon_int.PFM_PMU_MIPS_5KC
PFM_PMU_MIPS_74K = _perfmon_int.PFM_PMU_MIPS_74K
PFM_PMU_MIPS_R10000 = _perfmon_int.PFM_PMU_MIPS_R10000
PFM_PMU_MIPS_R12000 = _perfmon_int.PFM_PMU_MIPS_R12000
PFM_PMU_MIPS_RM7000 = _perfmon_int.PFM_PMU_MIPS_RM7000
PFM_PMU_MIPS_RM9000 = _perfmon_int.PFM_PMU_MIPS_RM9000
PFM_PMU_MIPS_SB1 = _perfmon_int.PFM_PMU_MIPS_SB1
PFM_PMU_MIPS_VR5432 = _perfmon_int.PFM_PMU_MIPS_VR5432
PFM_PMU_MIPS_VR5500 = _perfmon_int.PFM_PMU_MIPS_VR5500
PFM_PMU_MIPS_ICE9A = _perfmon_int.PFM_PMU_MIPS_ICE9A
PFM_PMU_MIPS_ICE9B = _perfmon_int.PFM_PMU_MIPS_ICE9B
PFM_PMU_POWERPC = _perfmon_int.PFM_PMU_POWERPC
PFM_PMU_CELL = _perfmon_int.PFM_PMU_CELL
PFM_PMU_SPARC_ULTRA12 = _perfmon_int.PFM_PMU_SPARC_ULTRA12
PFM_PMU_SPARC_ULTRA3 = _perfmon_int.PFM_PMU_SPARC_ULTRA3
PFM_PMU_SPARC_ULTRA3I = _perfmon_int.PFM_PMU_SPARC_ULTRA3I
PFM_PMU_SPARC_ULTRA3PLUS = _perfmon_int.PFM_PMU_SPARC_ULTRA3PLUS
PFM_PMU_SPARC_ULTRA4PLUS = _perfmon_int.PFM_PMU_SPARC_ULTRA4PLUS
PFM_PMU_SPARC_NIAGARA1 = _perfmon_int.PFM_PMU_SPARC_NIAGARA1
PFM_PMU_SPARC_NIAGARA2 = _perfmon_int.PFM_PMU_SPARC_NIAGARA2
PFM_PMU_PPC970 = _perfmon_int.PFM_PMU_PPC970
PFM_PMU_PPC970MP = _perfmon_int.PFM_PMU_PPC970MP
PFM_PMU_POWER3 = _perfmon_int.PFM_PMU_POWER3
PFM_PMU_POWER4 = _perfmon_int.PFM_PMU_POWER4
PFM_PMU_POWER5 = _perfmon_int.PFM_PMU_POWER5
PFM_PMU_POWER5p = _perfmon_int.PFM_PMU_POWER5p
PFM_PMU_POWER6 = _perfmon_int.PFM_PMU_POWER6
PFM_PMU_POWER7 = _perfmon_int.PFM_PMU_POWER7
PFM_PMU_PERF_EVENT = _perfmon_int.PFM_PMU_PERF_EVENT
PFM_PMU_INTEL_WSM = _perfmon_int.PFM_PMU_INTEL_WSM
PFM_PMU_INTEL_WSM_DP = _perfmon_int.PFM_PMU_INTEL_WSM_DP
PFM_PMU_INTEL_WSM_UNC = _perfmon_int.PFM_PMU_INTEL_WSM_UNC
PFM_PMU_AMD64_K7 = _perfmon_int.PFM_PMU_AMD64_K7
PFM_PMU_AMD64_K8_REVB = _perfmon_int.PFM_PMU_AMD64_K8_REVB
PFM_PMU_AMD64_K8_REVC = _perfmon_int.PFM_PMU_AMD64_K8_REVC
PFM_PMU_AMD64_K8_REVD = _perfmon_int.PFM_PMU_AMD64_K8_REVD
PFM_PMU_AMD64_K8_REVE = _perfmon_int.PFM_PMU_AMD64_K8_REVE
PFM_PMU_AMD64_K8_REVF = _perfmon_int.PFM_PMU_AMD64_K8_REVF
PFM_PMU_AMD64_K8_REVG = _perfmon_int.PFM_PMU_AMD64_K8_REVG
PFM_PMU_AMD64_FAM10H_BARCELONA = _perfmon_int.PFM_PMU_AMD64_FAM10H_BARCELONA
PFM_PMU_AMD64_FAM10H_SHANGHAI = _perfmon_int.PFM_PMU_AMD64_FAM10H_SHANGHAI
PFM_PMU_AMD64_FAM10H_ISTANBUL = _perfmon_int.PFM_PMU_AMD64_FAM10H_ISTANBUL
PFM_PMU_ARM_CORTEX_A8 = _perfmon_int.PFM_PMU_ARM_CORTEX_A8
PFM_PMU_ARM_CORTEX_A9 = _perfmon_int.PFM_PMU_ARM_CORTEX_A9
PFM_PMU_TORRENT = _perfmon_int.PFM_PMU_TORRENT
PFM_PMU_INTEL_SNB = _perfmon_int.PFM_PMU_INTEL_SNB
PFM_PMU_AMD64_FAM14H_BOBCAT = _perfmon_int.PFM_PMU_AMD64_FAM14H_BOBCAT
PFM_PMU_AMD64_FAM15H_INTERLAGOS = _perfmon_int.PFM_PMU_AMD64_FAM15H_INTERLAGOS
PFM_PMU_INTEL_SNB_EP = _perfmon_int.PFM_PMU_INTEL_SNB_EP
PFM_PMU_AMD64_FAM12H_LLANO = _perfmon_int.PFM_PMU_AMD64_FAM12H_LLANO
PFM_PMU_AMD64_FAM11H_TURION = _perfmon_int.PFM_PMU_AMD64_FAM11H_TURION
PFM_PMU_INTEL_IVB = _perfmon_int.PFM_PMU_INTEL_IVB
PFM_PMU_ARM_CORTEX_A15 = _perfmon_int.PFM_PMU_ARM_CORTEX_A15
PFM_PMU_INTEL_SNB_UNC_CB0 = _perfmon_int.PFM_PMU_INTEL_SNB_UNC_CB0
PFM_PMU_INTEL_SNB_UNC_CB1 = _perfmon_int.PFM_PMU_INTEL_SNB_UNC_CB1
PFM_PMU_INTEL_SNB_UNC_CB2 = _perfmon_int.PFM_PMU_INTEL_SNB_UNC_CB2
PFM_PMU_INTEL_SNB_UNC_CB3 = _perfmon_int.PFM_PMU_INTEL_SNB_UNC_CB3
PFM_PMU_INTEL_SNBEP_UNC_CB0 = _perfmon_int.PFM_PMU_INTEL_SNBEP_UNC_CB0
PFM_PMU_INTEL_SNBEP_UNC_CB1 = _perfmon_int.PFM_PMU_INTEL_SNBEP_UNC_CB1
PFM_PMU_INTEL_SNBEP_UNC_CB2 = _perfmon_int.PFM_PMU_INTEL_SNBEP_UNC_CB2
PFM_PMU_INTEL_SNBEP_UNC_CB3 = _perfmon_int.PFM_PMU_INTEL_SNBEP_UNC_CB3
PFM_PMU_INTEL_SNBEP_UNC_CB4 = _perfmon_int.PFM_PMU_INTEL_SNBEP_UNC_CB4
PFM_PMU_INTEL_SNBEP_UNC_CB5 = _perfmon_int.PFM_PMU_INTEL_SNBEP_UNC_CB5
PFM_PMU_INTEL_SNBEP_UNC_CB6 = _perfmon_int.PFM_PMU_INTEL_SNBEP_UNC_CB6
PFM_PMU_INTEL_SNBEP_UNC_CB7 = _perfmon_int.PFM_PMU_INTEL_SNBEP_UNC_CB7
PFM_PMU_INTEL_SNBEP_UNC_HA = _perfmon_int.PFM_PMU_INTEL_SNBEP_UNC_HA
PFM_PMU_INTEL_SNBEP_UNC_IMC0 = _perfmon_int.PFM_PMU_INTEL_SNBEP_UNC_IMC0
PFM_PMU_INTEL_SNBEP_UNC_IMC1 = _perfmon_int.PFM_PMU_INTEL_SNBEP_UNC_IMC1
PFM_PMU_INTEL_SNBEP_UNC_IMC2 = _perfmon_int.PFM_PMU_INTEL_SNBEP_UNC_IMC2
PFM_PMU_INTEL_SNBEP_UNC_IMC3 = _perfmon_int.PFM_PMU_INTEL_SNBEP_UNC_IMC3
PFM_PMU_INTEL_SNBEP_UNC_PCU = _perfmon_int.PFM_PMU_INTEL_SNBEP_UNC_PCU
PFM_PMU_INTEL_SNBEP_UNC_QPI0 = _perfmon_int.PFM_PMU_INTEL_SNBEP_UNC_QPI0
PFM_PMU_INTEL_SNBEP_UNC_QPI1 = _perfmon_int.PFM_PMU_INTEL_SNBEP_UNC_QPI1
PFM_PMU_INTEL_SNBEP_UNC_UBOX = _perfmon_int.PFM_PMU_INTEL_SNBEP_UNC_UBOX
PFM_PMU_INTEL_SNBEP_UNC_R2PCIE = _perfmon_int.PFM_PMU_INTEL_SNBEP_UNC_R2PCIE
PFM_PMU_INTEL_SNBEP_UNC_R3QPI0 = _perfmon_int.PFM_PMU_INTEL_SNBEP_UNC_R3QPI0
PFM_PMU_INTEL_SNBEP_UNC_R3QPI1 = _perfmon_int.PFM_PMU_INTEL_SNBEP_UNC_R3QPI1
PFM_PMU_INTEL_KNC = _perfmon_int.PFM_PMU_INTEL_KNC
PFM_PMU_S390X_CPUM_CF = _perfmon_int.PFM_PMU_S390X_CPUM_CF
PFM_PMU_ARM_1176 = _perfmon_int.PFM_PMU_ARM_1176
PFM_PMU_INTEL_IVB_EP = _perfmon_int.PFM_PMU_INTEL_IVB_EP
PFM_PMU_INTEL_HSW = _perfmon_int.PFM_PMU_INTEL_HSW
PFM_PMU_INTEL_IVB_UNC_CB0 = _perfmon_int.PFM_PMU_INTEL_IVB_UNC_CB0
PFM_PMU_INTEL_IVB_UNC_CB1 = _perfmon_int.PFM_PMU_INTEL_IVB_UNC_CB1
PFM_PMU_INTEL_IVB_UNC_CB2 = _perfmon_int.PFM_PMU_INTEL_IVB_UNC_CB2
PFM_PMU_INTEL_IVB_UNC_CB3 = _perfmon_int.PFM_PMU_INTEL_IVB_UNC_CB3
PFM_PMU_POWER8 = _perfmon_int.PFM_PMU_POWER8
PFM_PMU_INTEL_RAPL = _perfmon_int.PFM_PMU_INTEL_RAPL
PFM_PMU_INTEL_SLM = _perfmon_int.PFM_PMU_INTEL_SLM
PFM_PMU_AMD64_FAM15H_NB = _perfmon_int.PFM_PMU_AMD64_FAM15H_NB
PFM_PMU_ARM_QCOM_KRAIT = _perfmon_int.PFM_PMU_ARM_QCOM_KRAIT
PFM_PMU_PERF_EVENT_RAW = _perfmon_int.PFM_PMU_PERF_EVENT_RAW
PFM_PMU_INTEL_IVBEP_UNC_CB0 = _perfmon_int.PFM_PMU_INTEL_IVBEP_UNC_CB0
PFM_PMU_INTEL_IVBEP_UNC_CB1 = _perfmon_int.PFM_PMU_INTEL_IVBEP_UNC_CB1
PFM_PMU_INTEL_IVBEP_UNC_CB2 = _perfmon_int.PFM_PMU_INTEL_IVBEP_UNC_CB2
PFM_PMU_INTEL_IVBEP_UNC_CB3 = _perfmon_int.PFM_PMU_INTEL_IVBEP_UNC_CB3
PFM_PMU_INTEL_IVBEP_UNC_CB4 = _perfmon_int.PFM_PMU_INTEL_IVBEP_UNC_CB4
PFM_PMU_INTEL_IVBEP_UNC_CB5 = _perfmon_int.PFM_PMU_INTEL_IVBEP_UNC_CB5
PFM_PMU_INTEL_IVBEP_UNC_CB6 = _perfmon_int.PFM_PMU_INTEL_IVBEP_UNC_CB6
PFM_PMU_INTEL_IVBEP_UNC_CB7 = _perfmon_int.PFM_PMU_INTEL_IVBEP_UNC_CB7
PFM_PMU_INTEL_IVBEP_UNC_CB8 = _perfmon_int.PFM_PMU_INTEL_IVBEP_UNC_CB8
PFM_PMU_INTEL_IVBEP_UNC_CB9 = _perfmon_int.PFM_PMU_INTEL_IVBEP_UNC_CB9
PFM_PMU_INTEL_IVBEP_UNC_CB10 = _perfmon_int.PFM_PMU_INTEL_IVBEP_UNC_CB10
PFM_PMU_INTEL_IVBEP_UNC_CB11 = _perfmon_int.PFM_PMU_INTEL_IVBEP_UNC_CB11
PFM_PMU_INTEL_IVBEP_UNC_CB12 = _perfmon_int.PFM_PMU_INTEL_IVBEP_UNC_CB12
PFM_PMU_INTEL_IVBEP_UNC_CB13 = _perfmon_int.PFM_PMU_INTEL_IVBEP_UNC_CB13
PFM_PMU_INTEL_IVBEP_UNC_CB14 = _perfmon_int.PFM_PMU_INTEL_IVBEP_UNC_CB14
PFM_PMU_INTEL_IVBEP_UNC_HA0 = _perfmon_int.PFM_PMU_INTEL_IVBEP_UNC_HA0
PFM_PMU_INTEL_IVBEP_UNC_HA1 = _perfmon_int.PFM_PMU_INTEL_IVBEP_UNC_HA1
PFM_PMU_INTEL_IVBEP_UNC_IMC0 = _perfmon_int.PFM_PMU_INTEL_IVBEP_UNC_IMC0
PFM_PMU_INTEL_IVBEP_UNC_IMC1 = _perfmon_int.PFM_PMU_INTEL_IVBEP_UNC_IMC1
PFM_PMU_INTEL_IVBEP_UNC_IMC2 = _perfmon_int.PFM_PMU_INTEL_IVBEP_UNC_IMC2
PFM_PMU_INTEL_IVBEP_UNC_IMC3 = _perfmon_int.PFM_PMU_INTEL_IVBEP_UNC_IMC3
PFM_PMU_INTEL_IVBEP_UNC_IMC4 = _perfmon_int.PFM_PMU_INTEL_IVBEP_UNC_IMC4
PFM_PMU_INTEL_IVBEP_UNC_IMC5 = _perfmon_int.PFM_PMU_INTEL_IVBEP_UNC_IMC5
PFM_PMU_INTEL_IVBEP_UNC_IMC6 = _perfmon_int.PFM_PMU_INTEL_IVBEP_UNC_IMC6
PFM_PMU_INTEL_IVBEP_UNC_IMC7 = _perfmon_int.PFM_PMU_INTEL_IVBEP_UNC_IMC7
PFM_PMU_INTEL_IVBEP_UNC_PCU = _perfmon_int.PFM_PMU_INTEL_IVBEP_UNC_PCU
PFM_PMU_INTEL_IVBEP_UNC_QPI0 = _perfmon_int.PFM_PMU_INTEL_IVBEP_UNC_QPI0
PFM_PMU_INTEL_IVBEP_UNC_QPI1 = _perfmon_int.PFM_PMU_INTEL_IVBEP_UNC_QPI1
PFM_PMU_INTEL_IVBEP_UNC_QPI2 = _perfmon_int.PFM_PMU_INTEL_IVBEP_UNC_QPI2
PFM_PMU_INTEL_IVBEP_UNC_UBOX = _perfmon_int.PFM_PMU_INTEL_IVBEP_UNC_UBOX
PFM_PMU_INTEL_IVBEP_UNC_R2PCIE = _perfmon_int.PFM_PMU_INTEL_IVBEP_UNC_R2PCIE
PFM_PMU_INTEL_IVBEP_UNC_R3QPI0 = _perfmon_int.PFM_PMU_INTEL_IVBEP_UNC_R3QPI0
PFM_PMU_INTEL_IVBEP_UNC_R3QPI1 = _perfmon_int.PFM_PMU_INTEL_IVBEP_UNC_R3QPI1
PFM_PMU_INTEL_IVBEP_UNC_R3QPI2 = _perfmon_int.PFM_PMU_INTEL_IVBEP_UNC_R3QPI2
PFM_PMU_INTEL_IVBEP_UNC_IRP = _perfmon_int.PFM_PMU_INTEL_IVBEP_UNC_IRP
PFM_PMU_S390X_CPUM_SF = _perfmon_int.PFM_PMU_S390X_CPUM_SF
PFM_PMU_ARM_CORTEX_A57 = _perfmon_int.PFM_PMU_ARM_CORTEX_A57
PFM_PMU_ARM_CORTEX_A53 = _perfmon_int.PFM_PMU_ARM_CORTEX_A53
PFM_PMU_ARM_CORTEX_A7 = _perfmon_int.PFM_PMU_ARM_CORTEX_A7
PFM_PMU_INTEL_HSW_EP = _perfmon_int.PFM_PMU_INTEL_HSW_EP
PFM_PMU_INTEL_BDW = _perfmon_int.PFM_PMU_INTEL_BDW
PFM_PMU_ARM_XGENE = _perfmon_int.PFM_PMU_ARM_XGENE
PFM_PMU_INTEL_HSWEP_UNC_CB0 = _perfmon_int.PFM_PMU_INTEL_HSWEP_UNC_CB0
PFM_PMU_INTEL_HSWEP_UNC_CB1 = _perfmon_int.PFM_PMU_INTEL_HSWEP_UNC_CB1
PFM_PMU_INTEL_HSWEP_UNC_CB2 = _perfmon_int.PFM_PMU_INTEL_HSWEP_UNC_CB2
PFM_PMU_INTEL_HSWEP_UNC_CB3 = _perfmon_int.PFM_PMU_INTEL_HSWEP_UNC_CB3
PFM_PMU_INTEL_HSWEP_UNC_CB4 = _perfmon_int.PFM_PMU_INTEL_HSWEP_UNC_CB4
PFM_PMU_INTEL_HSWEP_UNC_CB5 = _perfmon_int.PFM_PMU_INTEL_HSWEP_UNC_CB5
PFM_PMU_INTEL_HSWEP_UNC_CB6 = _perfmon_int.PFM_PMU_INTEL_HSWEP_UNC_CB6
PFM_PMU_INTEL_HSWEP_UNC_CB7 = _perfmon_int.PFM_PMU_INTEL_HSWEP_UNC_CB7
PFM_PMU_INTEL_HSWEP_UNC_CB8 = _perfmon_int.PFM_PMU_INTEL_HSWEP_UNC_CB8
PFM_PMU_INTEL_HSWEP_UNC_CB9 = _perfmon_int.PFM_PMU_INTEL_HSWEP_UNC_CB9
PFM_PMU_INTEL_HSWEP_UNC_CB10 = _perfmon_int.PFM_PMU_INTEL_HSWEP_UNC_CB10
PFM_PMU_INTEL_HSWEP_UNC_CB11 = _perfmon_int.PFM_PMU_INTEL_HSWEP_UNC_CB11
PFM_PMU_INTEL_HSWEP_UNC_CB12 = _perfmon_int.PFM_PMU_INTEL_HSWEP_UNC_CB12
PFM_PMU_INTEL_HSWEP_UNC_CB13 = _perfmon_int.PFM_PMU_INTEL_HSWEP_UNC_CB13
PFM_PMU_INTEL_HSWEP_UNC_CB14 = _perfmon_int.PFM_PMU_INTEL_HSWEP_UNC_CB14
PFM_PMU_INTEL_HSWEP_UNC_CB15 = _perfmon_int.PFM_PMU_INTEL_HSWEP_UNC_CB15
PFM_PMU_INTEL_HSWEP_UNC_CB16 = _perfmon_int.PFM_PMU_INTEL_HSWEP_UNC_CB16
PFM_PMU_INTEL_HSWEP_UNC_CB17 = _perfmon_int.PFM_PMU_INTEL_HSWEP_UNC_CB17
PFM_PMU_INTEL_HSWEP_UNC_HA0 = _perfmon_int.PFM_PMU_INTEL_HSWEP_UNC_HA0
PFM_PMU_INTEL_HSWEP_UNC_HA1 = _perfmon_int.PFM_PMU_INTEL_HSWEP_UNC_HA1
PFM_PMU_INTEL_HSWEP_UNC_IMC0 = _perfmon_int.PFM_PMU_INTEL_HSWEP_UNC_IMC0
PFM_PMU_INTEL_HSWEP_UNC_IMC1 = _perfmon_int.PFM_PMU_INTEL_HSWEP_UNC_IMC1
PFM_PMU_INTEL_HSWEP_UNC_IMC2 = _perfmon_int.PFM_PMU_INTEL_HSWEP_UNC_IMC2
PFM_PMU_INTEL_HSWEP_UNC_IMC3 = _perfmon_int.PFM_PMU_INTEL_HSWEP_UNC_IMC3
PFM_PMU_INTEL_HSWEP_UNC_IMC4 = _perfmon_int.PFM_PMU_INTEL_HSWEP_UNC_IMC4
PFM_PMU_INTEL_HSWEP_UNC_IMC5 = _perfmon_int.PFM_PMU_INTEL_HSWEP_UNC_IMC5
PFM_PMU_INTEL_HSWEP_UNC_IMC6 = _perfmon_int.PFM_PMU_INTEL_HSWEP_UNC_IMC6
PFM_PMU_INTEL_HSWEP_UNC_IMC7 = _perfmon_int.PFM_PMU_INTEL_HSWEP_UNC_IMC7
PFM_PMU_INTEL_HSWEP_UNC_PCU = _perfmon_int.PFM_PMU_INTEL_HSWEP_UNC_PCU
PFM_PMU_INTEL_HSWEP_UNC_QPI0 = _perfmon_int.PFM_PMU_INTEL_HSWEP_UNC_QPI0
PFM_PMU_INTEL_HSWEP_UNC_QPI1 = _perfmon_int.PFM_PMU_INTEL_HSWEP_UNC_QPI1
PFM_PMU_INTEL_HSWEP_UNC_UBOX = _perfmon_int.PFM_PMU_INTEL_HSWEP_UNC_UBOX
PFM_PMU_INTEL_HSWEP_UNC_R2PCIE = _perfmon_int.PFM_PMU_INTEL_HSWEP_UNC_R2PCIE
PFM_PMU_INTEL_HSWEP_UNC_R3QPI0 = _perfmon_int.PFM_PMU_INTEL_HSWEP_UNC_R3QPI0
PFM_PMU_INTEL_HSWEP_UNC_R3QPI1 = _perfmon_int.PFM_PMU_INTEL_HSWEP_UNC_R3QPI1
PFM_PMU_INTEL_HSWEP_UNC_R3QPI2 = _perfmon_int.PFM_PMU_INTEL_HSWEP_UNC_R3QPI2
PFM_PMU_INTEL_HSWEP_UNC_IRP = _perfmon_int.PFM_PMU_INTEL_HSWEP_UNC_IRP
PFM_PMU_INTEL_HSWEP_UNC_SB0 = _perfmon_int.PFM_PMU_INTEL_HSWEP_UNC_SB0
PFM_PMU_INTEL_HSWEP_UNC_SB1 = _perfmon_int.PFM_PMU_INTEL_HSWEP_UNC_SB1
PFM_PMU_INTEL_HSWEP_UNC_SB2 = _perfmon_int.PFM_PMU_INTEL_HSWEP_UNC_SB2
PFM_PMU_INTEL_HSWEP_UNC_SB3 = _perfmon_int.PFM_PMU_INTEL_HSWEP_UNC_SB3
PFM_PMU_POWERPC_NEST_MCS_READ_BW = _perfmon_int.PFM_PMU_POWERPC_NEST_MCS_READ_BW
PFM_PMU_POWERPC_NEST_MCS_WRITE_BW = _perfmon_int.PFM_PMU_POWERPC_NEST_MCS_WRITE_BW
PFM_PMU_INTEL_SKL = _perfmon_int.PFM_PMU_INTEL_SKL
PFM_PMU_INTEL_BDW_EP = _perfmon_int.PFM_PMU_INTEL_BDW_EP
PFM_PMU_INTEL_GLM = _perfmon_int.PFM_PMU_INTEL_GLM
PFM_PMU_INTEL_KNL = _perfmon_int.PFM_PMU_INTEL_KNL
PFM_PMU_INTEL_KNL_UNC_IMC0 = _perfmon_int.PFM_PMU_INTEL_KNL_UNC_IMC0
PFM_PMU_INTEL_KNL_UNC_IMC1 = _perfmon_int.PFM_PMU_INTEL_KNL_UNC_IMC1
PFM_PMU_INTEL_KNL_UNC_IMC2 = _perfmon_int.PFM_PMU_INTEL_KNL_UNC_IMC2
PFM_PMU_INTEL_KNL_UNC_IMC3 = _perfmon_int.PFM_PMU_INTEL_KNL_UNC_IMC3
PFM_PMU_INTEL_KNL_UNC_IMC4 = _perfmon_int.PFM_PMU_INTEL_KNL_UNC_IMC4
PFM_PMU_INTEL_KNL_UNC_IMC5 = _perfmon_int.PFM_PMU_INTEL_KNL_UNC_IMC5
PFM_PMU_INTEL_KNL_UNC_IMC_UCLK0 = _perfmon_int.PFM_PMU_INTEL_KNL_UNC_IMC_UCLK0
PFM_PMU_INTEL_KNL_UNC_IMC_UCLK1 = _perfmon_int.PFM_PMU_INTEL_KNL_UNC_IMC_UCLK1
PFM_PMU_INTEL_KNL_UNC_EDC_ECLK0 = _perfmon_int.PFM_PMU_INTEL_KNL_UNC_EDC_ECLK0
PFM_PMU_INTEL_KNL_UNC_EDC_ECLK1 = _perfmon_int.PFM_PMU_INTEL_KNL_UNC_EDC_ECLK1
PFM_PMU_INTEL_KNL_UNC_EDC_ECLK2 = _perfmon_int.PFM_PMU_INTEL_KNL_UNC_EDC_ECLK2
PFM_PMU_INTEL_KNL_UNC_EDC_ECLK3 = _perfmon_int.PFM_PMU_INTEL_KNL_UNC_EDC_ECLK3
PFM_PMU_INTEL_KNL_UNC_EDC_ECLK4 = _perfmon_int.PFM_PMU_INTEL_KNL_UNC_EDC_ECLK4
PFM_PMU_INTEL_KNL_UNC_EDC_ECLK5 = _perfmon_int.PFM_PMU_INTEL_KNL_UNC_EDC_ECLK5
PFM_PMU_INTEL_KNL_UNC_EDC_ECLK6 = _perfmon_int.PFM_PMU_INTEL_KNL_UNC_EDC_ECLK6
PFM_PMU_INTEL_KNL_UNC_EDC_ECLK7 = _perfmon_int.PFM_PMU_INTEL_KNL_UNC_EDC_ECLK7
PFM_PMU_INTEL_KNL_UNC_EDC_UCLK0 = _perfmon_int.PFM_PMU_INTEL_KNL_UNC_EDC_UCLK0
PFM_PMU_INTEL_KNL_UNC_EDC_UCLK1 = _perfmon_int.PFM_PMU_INTEL_KNL_UNC_EDC_UCLK1
PFM_PMU_INTEL_KNL_UNC_EDC_UCLK2 = _perfmon_int.PFM_PMU_INTEL_KNL_UNC_EDC_UCLK2
PFM_PMU_INTEL_KNL_UNC_EDC_UCLK3 = _perfmon_int.PFM_PMU_INTEL_KNL_UNC_EDC_UCLK3
PFM_PMU_INTEL_KNL_UNC_EDC_UCLK4 = _perfmon_int.PFM_PMU_INTEL_KNL_UNC_EDC_UCLK4
PFM_PMU_INTEL_KNL_UNC_EDC_UCLK5 = _perfmon_int.PFM_PMU_INTEL_KNL_UNC_EDC_UCLK5
PFM_PMU_INTEL_KNL_UNC_EDC_UCLK6 = _perfmon_int.PFM_PMU_INTEL_KNL_UNC_EDC_UCLK6
PFM_PMU_INTEL_KNL_UNC_EDC_UCLK7 = _perfmon_int.PFM_PMU_INTEL_KNL_UNC_EDC_UCLK7
PFM_PMU_INTEL_KNL_UNC_CHA0 = _perfmon_int.PFM_PMU_INTEL_KNL_UNC_CHA0
PFM_PMU_INTEL_KNL_UNC_CHA1 = _perfmon_int.PFM_PMU_INTEL_KNL_UNC_CHA1
PFM_PMU_INTEL_KNL_UNC_CHA2 = _perfmon_int.PFM_PMU_INTEL_KNL_UNC_CHA2
PFM_PMU_INTEL_KNL_UNC_CHA3 = _perfmon_int.PFM_PMU_INTEL_KNL_UNC_CHA3
PFM_PMU_INTEL_KNL_UNC_CHA4 = _perfmon_int.PFM_PMU_INTEL_KNL_UNC_CHA4
PFM_PMU_INTEL_KNL_UNC_CHA5 = _perfmon_int.PFM_PMU_INTEL_KNL_UNC_CHA5
PFM_PMU_INTEL_KNL_UNC_CHA6 = _perfmon_int.PFM_PMU_INTEL_KNL_UNC_CHA6
PFM_PMU_INTEL_KNL_UNC_CHA7 = _perfmon_int.PFM_PMU_INTEL_KNL_UNC_CHA7
PFM_PMU_INTEL_KNL_UNC_CHA8 = _perfmon_int.PFM_PMU_INTEL_KNL_UNC_CHA8
PFM_PMU_INTEL_KNL_UNC_CHA9 = _perfmon_int.PFM_PMU_INTEL_KNL_UNC_CHA9
PFM_PMU_INTEL_KNL_UNC_CHA10 = _perfmon_int.PFM_PMU_INTEL_KNL_UNC_CHA10
PFM_PMU_INTEL_KNL_UNC_CHA11 = _perfmon_int.PFM_PMU_INTEL_KNL_UNC_CHA11
PFM_PMU_INTEL_KNL_UNC_CHA12 = _perfmon_int.PFM_PMU_INTEL_KNL_UNC_CHA12
PFM_PMU_INTEL_KNL_UNC_CHA13 = _perfmon_int.PFM_PMU_INTEL_KNL_UNC_CHA13
PFM_PMU_INTEL_KNL_UNC_CHA14 = _perfmon_int.PFM_PMU_INTEL_KNL_UNC_CHA14
PFM_PMU_INTEL_KNL_UNC_CHA15 = _perfmon_int.PFM_PMU_INTEL_KNL_UNC_CHA15
PFM_PMU_INTEL_KNL_UNC_CHA16 = _perfmon_int.PFM_PMU_INTEL_KNL_UNC_CHA16
PFM_PMU_INTEL_KNL_UNC_CHA17 = _perfmon_int.PFM_PMU_INTEL_KNL_UNC_CHA17
PFM_PMU_INTEL_KNL_UNC_CHA18 = _perfmon_int.PFM_PMU_INTEL_KNL_UNC_CHA18
PFM_PMU_INTEL_KNL_UNC_CHA19 = _perfmon_int.PFM_PMU_INTEL_KNL_UNC_CHA19
PFM_PMU_INTEL_KNL_UNC_CHA20 = _perfmon_int.PFM_PMU_INTEL_KNL_UNC_CHA20
PFM_PMU_INTEL_KNL_UNC_CHA21 = _perfmon_int.PFM_PMU_INTEL_KNL_UNC_CHA21
PFM_PMU_INTEL_KNL_UNC_CHA22 = _perfmon_int.PFM_PMU_INTEL_KNL_UNC_CHA22
PFM_PMU_INTEL_KNL_UNC_CHA23 = _perfmon_int.PFM_PMU_INTEL_KNL_UNC_CHA23
PFM_PMU_INTEL_KNL_UNC_CHA24 = _perfmon_int.PFM_PMU_INTEL_KNL_UNC_CHA24
PFM_PMU_INTEL_KNL_UNC_CHA25 = _perfmon_int.PFM_PMU_INTEL_KNL_UNC_CHA25
PFM_PMU_INTEL_KNL_UNC_CHA26 = _perfmon_int.PFM_PMU_INTEL_KNL_UNC_CHA26
PFM_PMU_INTEL_KNL_UNC_CHA27 = _perfmon_int.PFM_PMU_INTEL_KNL_UNC_CHA27
PFM_PMU_INTEL_KNL_UNC_CHA28 = _perfmon_int.PFM_PMU_INTEL_KNL_UNC_CHA28
PFM_PMU_INTEL_KNL_UNC_CHA29 = _perfmon_int.PFM_PMU_INTEL_KNL_UNC_CHA29
PFM_PMU_INTEL_KNL_UNC_CHA30 = _perfmon_int.PFM_PMU_INTEL_KNL_UNC_CHA30
PFM_PMU_INTEL_KNL_UNC_CHA31 = _perfmon_int.PFM_PMU_INTEL_KNL_UNC_CHA31
PFM_PMU_INTEL_KNL_UNC_CHA32 = _perfmon_int.PFM_PMU_INTEL_KNL_UNC_CHA32
PFM_PMU_INTEL_KNL_UNC_CHA33 = _perfmon_int.PFM_PMU_INTEL_KNL_UNC_CHA33
PFM_PMU_INTEL_KNL_UNC_CHA34 = _perfmon_int.PFM_PMU_INTEL_KNL_UNC_CHA34
PFM_PMU_INTEL_KNL_UNC_CHA35 = _perfmon_int.PFM_PMU_INTEL_KNL_UNC_CHA35
PFM_PMU_INTEL_KNL_UNC_CHA36 = _perfmon_int.PFM_PMU_INTEL_KNL_UNC_CHA36
PFM_PMU_INTEL_KNL_UNC_CHA37 = _perfmon_int.PFM_PMU_INTEL_KNL_UNC_CHA37
PFM_PMU_INTEL_KNL_UNC_UBOX = _perfmon_int.PFM_PMU_INTEL_KNL_UNC_UBOX
PFM_PMU_INTEL_KNL_UNC_M2PCIE = _perfmon_int.PFM_PMU_INTEL_KNL_UNC_M2PCIE
PFM_PMU_POWER9 = _perfmon_int.PFM_PMU_POWER9
PFM_PMU_INTEL_BDX_UNC_CB0 = _perfmon_int.PFM_PMU_INTEL_BDX_UNC_CB0
PFM_PMU_INTEL_BDX_UNC_CB1 = _perfmon_int.PFM_PMU_INTEL_BDX_UNC_CB1
PFM_PMU_INTEL_BDX_UNC_CB2 = _perfmon_int.PFM_PMU_INTEL_BDX_UNC_CB2
PFM_PMU_INTEL_BDX_UNC_CB3 = _perfmon_int.PFM_PMU_INTEL_BDX_UNC_CB3
PFM_PMU_INTEL_BDX_UNC_CB4 = _perfmon_int.PFM_PMU_INTEL_BDX_UNC_CB4
PFM_PMU_INTEL_BDX_UNC_CB5 = _perfmon_int.PFM_PMU_INTEL_BDX_UNC_CB5
PFM_PMU_INTEL_BDX_UNC_CB6 = _perfmon_int.PFM_PMU_INTEL_BDX_UNC_CB6
PFM_PMU_INTEL_BDX_UNC_CB7 = _perfmon_int.PFM_PMU_INTEL_BDX_UNC_CB7
PFM_PMU_INTEL_BDX_UNC_CB8 = _perfmon_int.PFM_PMU_INTEL_BDX_UNC_CB8
PFM_PMU_INTEL_BDX_UNC_CB9 = _perfmon_int.PFM_PMU_INTEL_BDX_UNC_CB9
PFM_PMU_INTEL_BDX_UNC_CB10 = _perfmon_int.PFM_PMU_INTEL_BDX_UNC_CB10
PFM_PMU_INTEL_BDX_UNC_CB11 = _perfmon_int.PFM_PMU_INTEL_BDX_UNC_CB11
PFM_PMU_INTEL_BDX_UNC_CB12 = _perfmon_int.PFM_PMU_INTEL_BDX_UNC_CB12
PFM_PMU_INTEL_BDX_UNC_CB13 = _perfmon_int.PFM_PMU_INTEL_BDX_UNC_CB13
PFM_PMU_INTEL_BDX_UNC_CB14 = _perfmon_int.PFM_PMU_INTEL_BDX_UNC_CB14
PFM_PMU_INTEL_BDX_UNC_CB15 = _perfmon_int.PFM_PMU_INTEL_BDX_UNC_CB15
PFM_PMU_INTEL_BDX_UNC_CB16 = _perfmon_int.PFM_PMU_INTEL_BDX_UNC_CB16
PFM_PMU_INTEL_BDX_UNC_CB17 = _perfmon_int.PFM_PMU_INTEL_BDX_UNC_CB17
PFM_PMU_INTEL_BDX_UNC_CB18 = _perfmon_int.PFM_PMU_INTEL_BDX_UNC_CB18
PFM_PMU_INTEL_BDX_UNC_CB19 = _perfmon_int.PFM_PMU_INTEL_BDX_UNC_CB19
PFM_PMU_INTEL_BDX_UNC_CB20 = _perfmon_int.PFM_PMU_INTEL_BDX_UNC_CB20
PFM_PMU_INTEL_BDX_UNC_CB21 = _perfmon_int.PFM_PMU_INTEL_BDX_UNC_CB21
PFM_PMU_INTEL_BDX_UNC_CB22 = _perfmon_int.PFM_PMU_INTEL_BDX_UNC_CB22
PFM_PMU_INTEL_BDX_UNC_CB23 = _perfmon_int.PFM_PMU_INTEL_BDX_UNC_CB23
PFM_PMU_INTEL_BDX_UNC_HA0 = _perfmon_int.PFM_PMU_INTEL_BDX_UNC_HA0
PFM_PMU_INTEL_BDX_UNC_HA1 = _perfmon_int.PFM_PMU_INTEL_BDX_UNC_HA1
PFM_PMU_INTEL_BDX_UNC_IMC0 = _perfmon_int.PFM_PMU_INTEL_BDX_UNC_IMC0
PFM_PMU_INTEL_BDX_UNC_IMC1 = _perfmon_int.PFM_PMU_INTEL_BDX_UNC_IMC1
PFM_PMU_INTEL_BDX_UNC_IMC2 = _perfmon_int.PFM_PMU_INTEL_BDX_UNC_IMC2
PFM_PMU_INTEL_BDX_UNC_IMC3 = _perfmon_int.PFM_PMU_INTEL_BDX_UNC_IMC3
PFM_PMU_INTEL_BDX_UNC_IMC4 = _perfmon_int.PFM_PMU_INTEL_BDX_UNC_IMC4
PFM_PMU_INTEL_BDX_UNC_IMC5 = _perfmon_int.PFM_PMU_INTEL_BDX_UNC_IMC5
PFM_PMU_INTEL_BDX_UNC_IMC6 = _perfmon_int.PFM_PMU_INTEL_BDX_UNC_IMC6
PFM_PMU_INTEL_BDX_UNC_IMC7 = _perfmon_int.PFM_PMU_INTEL_BDX_UNC_IMC7
PFM_PMU_INTEL_BDX_UNC_PCU = _perfmon_int.PFM_PMU_INTEL_BDX_UNC_PCU
PFM_PMU_INTEL_BDX_UNC_QPI0 = _perfmon_int.PFM_PMU_INTEL_BDX_UNC_QPI0
PFM_PMU_INTEL_BDX_UNC_QPI1 = _perfmon_int.PFM_PMU_INTEL_BDX_UNC_QPI1
PFM_PMU_INTEL_BDX_UNC_QPI2 = _perfmon_int.PFM_PMU_INTEL_BDX_UNC_QPI2
PFM_PMU_INTEL_BDX_UNC_UBOX = _perfmon_int.PFM_PMU_INTEL_BDX_UNC_UBOX
PFM_PMU_INTEL_BDX_UNC_R2PCIE = _perfmon_int.PFM_PMU_INTEL_BDX_UNC_R2PCIE
PFM_PMU_INTEL_BDX_UNC_R3QPI0 = _perfmon_int.PFM_PMU_INTEL_BDX_UNC_R3QPI0
PFM_PMU_INTEL_BDX_UNC_R3QPI1 = _perfmon_int.PFM_PMU_INTEL_BDX_UNC_R3QPI1
PFM_PMU_INTEL_BDX_UNC_R3QPI2 = _perfmon_int.PFM_PMU_INTEL_BDX_UNC_R3QPI2
PFM_PMU_INTEL_BDX_UNC_IRP = _perfmon_int.PFM_PMU_INTEL_BDX_UNC_IRP
PFM_PMU_INTEL_BDX_UNC_SB0 = _perfmon_int.PFM_PMU_INTEL_BDX_UNC_SB0
PFM_PMU_INTEL_BDX_UNC_SB1 = _perfmon_int.PFM_PMU_INTEL_BDX_UNC_SB1
PFM_PMU_INTEL_BDX_UNC_SB2 = _perfmon_int.PFM_PMU_INTEL_BDX_UNC_SB2
PFM_PMU_INTEL_BDX_UNC_SB3 = _perfmon_int.PFM_PMU_INTEL_BDX_UNC_SB3
PFM_PMU_AMD64_FAM17H = _perfmon_int.PFM_PMU_AMD64_FAM17H
PFM_PMU_AMD64_FAM16H = _perfmon_int.PFM_PMU_AMD64_FAM16H
PFM_PMU_INTEL_SKX = _perfmon_int.PFM_PMU_INTEL_SKX
PFM_PMU_INTEL_SKX_UNC_CHA0 = _perfmon_int.PFM_PMU_INTEL_SKX_UNC_CHA0
PFM_PMU_INTEL_SKX_UNC_CHA1 = _perfmon_int.PFM_PMU_INTEL_SKX_UNC_CHA1
PFM_PMU_INTEL_SKX_UNC_CHA2 = _perfmon_int.PFM_PMU_INTEL_SKX_UNC_CHA2
PFM_PMU_INTEL_SKX_UNC_CHA3 = _perfmon_int.PFM_PMU_INTEL_SKX_UNC_CHA3
PFM_PMU_INTEL_SKX_UNC_CHA4 = _perfmon_int.PFM_PMU_INTEL_SKX_UNC_CHA4
PFM_PMU_INTEL_SKX_UNC_CHA5 = _perfmon_int.PFM_PMU_INTEL_SKX_UNC_CHA5
PFM_PMU_INTEL_SKX_UNC_CHA6 = _perfmon_int.PFM_PMU_INTEL_SKX_UNC_CHA6
PFM_PMU_INTEL_SKX_UNC_CHA7 = _perfmon_int.PFM_PMU_INTEL_SKX_UNC_CHA7
PFM_PMU_INTEL_SKX_UNC_CHA8 = _perfmon_int.PFM_PMU_INTEL_SKX_UNC_CHA8
PFM_PMU_INTEL_SKX_UNC_CHA9 = _perfmon_int.PFM_PMU_INTEL_SKX_UNC_CHA9
PFM_PMU_INTEL_SKX_UNC_CHA10 = _perfmon_int.PFM_PMU_INTEL_SKX_UNC_CHA10
PFM_PMU_INTEL_SKX_UNC_CHA11 = _perfmon_int.PFM_PMU_INTEL_SKX_UNC_CHA11
PFM_PMU_INTEL_SKX_UNC_CHA12 = _perfmon_int.PFM_PMU_INTEL_SKX_UNC_CHA12
PFM_PMU_INTEL_SKX_UNC_CHA13 = _perfmon_int.PFM_PMU_INTEL_SKX_UNC_CHA13
PFM_PMU_INTEL_SKX_UNC_CHA14 = _perfmon_int.PFM_PMU_INTEL_SKX_UNC_CHA14
PFM_PMU_INTEL_SKX_UNC_CHA15 = _perfmon_int.PFM_PMU_INTEL_SKX_UNC_CHA15
PFM_PMU_INTEL_SKX_UNC_CHA16 = _perfmon_int.PFM_PMU_INTEL_SKX_UNC_CHA16
PFM_PMU_INTEL_SKX_UNC_CHA17 = _perfmon_int.PFM_PMU_INTEL_SKX_UNC_CHA17
PFM_PMU_INTEL_SKX_UNC_CHA18 = _perfmon_int.PFM_PMU_INTEL_SKX_UNC_CHA18
PFM_PMU_INTEL_SKX_UNC_CHA19 = _perfmon_int.PFM_PMU_INTEL_SKX_UNC_CHA19
PFM_PMU_INTEL_SKX_UNC_CHA20 = _perfmon_int.PFM_PMU_INTEL_SKX_UNC_CHA20
PFM_PMU_INTEL_SKX_UNC_CHA21 = _perfmon_int.PFM_PMU_INTEL_SKX_UNC_CHA21
PFM_PMU_INTEL_SKX_UNC_CHA22 = _perfmon_int.PFM_PMU_INTEL_SKX_UNC_CHA22
PFM_PMU_INTEL_SKX_UNC_CHA23 = _perfmon_int.PFM_PMU_INTEL_SKX_UNC_CHA23
PFM_PMU_INTEL_SKX_UNC_CHA24 = _perfmon_int.PFM_PMU_INTEL_SKX_UNC_CHA24
PFM_PMU_INTEL_SKX_UNC_CHA25 = _perfmon_int.PFM_PMU_INTEL_SKX_UNC_CHA25
PFM_PMU_INTEL_SKX_UNC_CHA26 = _perfmon_int.PFM_PMU_INTEL_SKX_UNC_CHA26
PFM_PMU_INTEL_SKX_UNC_CHA27 = _perfmon_int.PFM_PMU_INTEL_SKX_UNC_CHA27
PFM_PMU_INTEL_SKX_UNC_IIO0 = _perfmon_int.PFM_PMU_INTEL_SKX_UNC_IIO0
PFM_PMU_INTEL_SKX_UNC_IIO1 = _perfmon_int.PFM_PMU_INTEL_SKX_UNC_IIO1
PFM_PMU_INTEL_SKX_UNC_IIO2 = _perfmon_int.PFM_PMU_INTEL_SKX_UNC_IIO2
PFM_PMU_INTEL_SKX_UNC_IIO3 = _perfmon_int.PFM_PMU_INTEL_SKX_UNC_IIO3
PFM_PMU_INTEL_SKX_UNC_IIO4 = _perfmon_int.PFM_PMU_INTEL_SKX_UNC_IIO4
PFM_PMU_INTEL_SKX_UNC_IIO5 = _perfmon_int.PFM_PMU_INTEL_SKX_UNC_IIO5
PFM_PMU_INTEL_SKX_UNC_IMC0 = _perfmon_int.PFM_PMU_INTEL_SKX_UNC_IMC0
PFM_PMU_INTEL_SKX_UNC_IMC1 = _perfmon_int.PFM_PMU_INTEL_SKX_UNC_IMC1
PFM_PMU_INTEL_SKX_UNC_IMC2 = _perfmon_int.PFM_PMU_INTEL_SKX_UNC_IMC2
PFM_PMU_INTEL_SKX_UNC_IMC3 = _perfmon_int.PFM_PMU_INTEL_SKX_UNC_IMC3
PFM_PMU_INTEL_SKX_UNC_IMC4 = _perfmon_int.PFM_PMU_INTEL_SKX_UNC_IMC4
PFM_PMU_INTEL_SKX_UNC_IMC5 = _perfmon_int.PFM_PMU_INTEL_SKX_UNC_IMC5
PFM_PMU_INTEL_SKX_UNC_IRP = _perfmon_int.PFM_PMU_INTEL_SKX_UNC_IRP
PFM_PMU_INTEL_SKX_UNC_M2M0 = _perfmon_int.PFM_PMU_INTEL_SKX_UNC_M2M0
PFM_PMU_INTEL_SKX_UNC_M2M1 = _perfmon_int.PFM_PMU_INTEL_SKX_UNC_M2M1
PFM_PMU_INTEL_SKX_UNC_M3UPI0 = _perfmon_int.PFM_PMU_INTEL_SKX_UNC_M3UPI0
PFM_PMU_INTEL_SKX_UNC_M3UPI1 = _perfmon_int.PFM_PMU_INTEL_SKX_UNC_M3UPI1
PFM_PMU_INTEL_SKX_UNC_M3UPI2 = _perfmon_int.PFM_PMU_INTEL_SKX_UNC_M3UPI2
PFM_PMU_INTEL_SKX_UNC_PCU = _perfmon_int.PFM_PMU_INTEL_SKX_UNC_PCU
PFM_PMU_INTEL_SKX_UNC_UBOX = _perfmon_int.PFM_PMU_INTEL_SKX_UNC_UBOX
PFM_PMU_INTEL_SKX_UNC_UPI0 = _perfmon_int.PFM_PMU_INTEL_SKX_UNC_UPI0
PFM_PMU_INTEL_SKX_UNC_UPI1 = _perfmon_int.PFM_PMU_INTEL_SKX_UNC_UPI1
PFM_PMU_INTEL_SKX_UNC_UPI2 = _perfmon_int.PFM_PMU_INTEL_SKX_UNC_UPI2
PFM_PMU_INTEL_KNM = _perfmon_int.PFM_PMU_INTEL_KNM
PFM_PMU_INTEL_KNM_UNC_IMC0 = _perfmon_int.PFM_PMU_INTEL_KNM_UNC_IMC0
PFM_PMU_INTEL_KNM_UNC_IMC1 = _perfmon_int.PFM_PMU_INTEL_KNM_UNC_IMC1
PFM_PMU_INTEL_KNM_UNC_IMC2 = _perfmon_int.PFM_PMU_INTEL_KNM_UNC_IMC2
PFM_PMU_INTEL_KNM_UNC_IMC3 = _perfmon_int.PFM_PMU_INTEL_KNM_UNC_IMC3
PFM_PMU_INTEL_KNM_UNC_IMC4 = _perfmon_int.PFM_PMU_INTEL_KNM_UNC_IMC4
PFM_PMU_INTEL_KNM_UNC_IMC5 = _perfmon_int.PFM_PMU_INTEL_KNM_UNC_IMC5
PFM_PMU_INTEL_KNM_UNC_IMC_UCLK0 = _perfmon_int.PFM_PMU_INTEL_KNM_UNC_IMC_UCLK0
PFM_PMU_INTEL_KNM_UNC_IMC_UCLK1 = _perfmon_int.PFM_PMU_INTEL_KNM_UNC_IMC_UCLK1
PFM_PMU_INTEL_KNM_UNC_EDC_ECLK0 = _perfmon_int.PFM_PMU_INTEL_KNM_UNC_EDC_ECLK0
PFM_PMU_INTEL_KNM_UNC_EDC_ECLK1 = _perfmon_int.PFM_PMU_INTEL_KNM_UNC_EDC_ECLK1
PFM_PMU_INTEL_KNM_UNC_EDC_ECLK2 = _perfmon_int.PFM_PMU_INTEL_KNM_UNC_EDC_ECLK2
PFM_PMU_INTEL_KNM_UNC_EDC_ECLK3 = _perfmon_int.PFM_PMU_INTEL_KNM_UNC_EDC_ECLK3
PFM_PMU_INTEL_KNM_UNC_EDC_ECLK4 = _perfmon_int.PFM_PMU_INTEL_KNM_UNC_EDC_ECLK4
PFM_PMU_INTEL_KNM_UNC_EDC_ECLK5 = _perfmon_int.PFM_PMU_INTEL_KNM_UNC_EDC_ECLK5
PFM_PMU_INTEL_KNM_UNC_EDC_ECLK6 = _perfmon_int.PFM_PMU_INTEL_KNM_UNC_EDC_ECLK6
PFM_PMU_INTEL_KNM_UNC_EDC_ECLK7 = _perfmon_int.PFM_PMU_INTEL_KNM_UNC_EDC_ECLK7
PFM_PMU_INTEL_KNM_UNC_EDC_UCLK0 = _perfmon_int.PFM_PMU_INTEL_KNM_UNC_EDC_UCLK0
PFM_PMU_INTEL_KNM_UNC_EDC_UCLK1 = _perfmon_int.PFM_PMU_INTEL_KNM_UNC_EDC_UCLK1
PFM_PMU_INTEL_KNM_UNC_EDC_UCLK2 = _perfmon_int.PFM_PMU_INTEL_KNM_UNC_EDC_UCLK2
PFM_PMU_INTEL_KNM_UNC_EDC_UCLK3 = _perfmon_int.PFM_PMU_INTEL_KNM_UNC_EDC_UCLK3
PFM_PMU_INTEL_KNM_UNC_EDC_UCLK4 = _perfmon_int.PFM_PMU_INTEL_KNM_UNC_EDC_UCLK4
PFM_PMU_INTEL_KNM_UNC_EDC_UCLK5 = _perfmon_int.PFM_PMU_INTEL_KNM_UNC_EDC_UCLK5
PFM_PMU_INTEL_KNM_UNC_EDC_UCLK6 = _perfmon_int.PFM_PMU_INTEL_KNM_UNC_EDC_UCLK6
PFM_PMU_INTEL_KNM_UNC_EDC_UCLK7 = _perfmon_int.PFM_PMU_INTEL_KNM_UNC_EDC_UCLK7
PFM_PMU_INTEL_KNM_UNC_CHA0 = _perfmon_int.PFM_PMU_INTEL_KNM_UNC_CHA0
PFM_PMU_INTEL_KNM_UNC_CHA1 = _perfmon_int.PFM_PMU_INTEL_KNM_UNC_CHA1
PFM_PMU_INTEL_KNM_UNC_CHA2 = _perfmon_int.PFM_PMU_INTEL_KNM_UNC_CHA2
PFM_PMU_INTEL_KNM_UNC_CHA3 = _perfmon_int.PFM_PMU_INTEL_KNM_UNC_CHA3
PFM_PMU_INTEL_KNM_UNC_CHA4 = _perfmon_int.PFM_PMU_INTEL_KNM_UNC_CHA4
PFM_PMU_INTEL_KNM_UNC_CHA5 = _perfmon_int.PFM_PMU_INTEL_KNM_UNC_CHA5
PFM_PMU_INTEL_KNM_UNC_CHA6 = _perfmon_int.PFM_PMU_INTEL_KNM_UNC_CHA6
PFM_PMU_INTEL_KNM_UNC_CHA7 = _perfmon_int.PFM_PMU_INTEL_KNM_UNC_CHA7
PFM_PMU_INTEL_KNM_UNC_CHA8 = _perfmon_int.PFM_PMU_INTEL_KNM_UNC_CHA8
PFM_PMU_INTEL_KNM_UNC_CHA9 = _perfmon_int.PFM_PMU_INTEL_KNM_UNC_CHA9
PFM_PMU_INTEL_KNM_UNC_CHA10 = _perfmon_int.PFM_PMU_INTEL_KNM_UNC_CHA10
PFM_PMU_INTEL_KNM_UNC_CHA11 = _perfmon_int.PFM_PMU_INTEL_KNM_UNC_CHA11
PFM_PMU_INTEL_KNM_UNC_CHA12 = _perfmon_int.PFM_PMU_INTEL_KNM_UNC_CHA12
PFM_PMU_INTEL_KNM_UNC_CHA13 = _perfmon_int.PFM_PMU_INTEL_KNM_UNC_CHA13
PFM_PMU_INTEL_KNM_UNC_CHA14 = _perfmon_int.PFM_PMU_INTEL_KNM_UNC_CHA14
PFM_PMU_INTEL_KNM_UNC_CHA15 = _perfmon_int.PFM_PMU_INTEL_KNM_UNC_CHA15
PFM_PMU_INTEL_KNM_UNC_CHA16 = _perfmon_int.PFM_PMU_INTEL_KNM_UNC_CHA16
PFM_PMU_INTEL_KNM_UNC_CHA17 = _perfmon_int.PFM_PMU_INTEL_KNM_UNC_CHA17
PFM_PMU_INTEL_KNM_UNC_CHA18 = _perfmon_int.PFM_PMU_INTEL_KNM_UNC_CHA18
PFM_PMU_INTEL_KNM_UNC_CHA19 = _perfmon_int.PFM_PMU_INTEL_KNM_UNC_CHA19
PFM_PMU_INTEL_KNM_UNC_CHA20 = _perfmon_int.PFM_PMU_INTEL_KNM_UNC_CHA20
PFM_PMU_INTEL_KNM_UNC_CHA21 = _perfmon_int.PFM_PMU_INTEL_KNM_UNC_CHA21
PFM_PMU_INTEL_KNM_UNC_CHA22 = _perfmon_int.PFM_PMU_INTEL_KNM_UNC_CHA22
PFM_PMU_INTEL_KNM_UNC_CHA23 = _perfmon_int.PFM_PMU_INTEL_KNM_UNC_CHA23
PFM_PMU_INTEL_KNM_UNC_CHA24 = _perfmon_int.PFM_PMU_INTEL_KNM_UNC_CHA24
PFM_PMU_INTEL_KNM_UNC_CHA25 = _perfmon_int.PFM_PMU_INTEL_KNM_UNC_CHA25
PFM_PMU_INTEL_KNM_UNC_CHA26 = _perfmon_int.PFM_PMU_INTEL_KNM_UNC_CHA26
PFM_PMU_INTEL_KNM_UNC_CHA27 = _perfmon_int.PFM_PMU_INTEL_KNM_UNC_CHA27
PFM_PMU_INTEL_KNM_UNC_CHA28 = _perfmon_int.PFM_PMU_INTEL_KNM_UNC_CHA28
PFM_PMU_INTEL_KNM_UNC_CHA29 = _perfmon_int.PFM_PMU_INTEL_KNM_UNC_CHA29
PFM_PMU_INTEL_KNM_UNC_CHA30 = _perfmon_int.PFM_PMU_INTEL_KNM_UNC_CHA30
PFM_PMU_INTEL_KNM_UNC_CHA31 = _perfmon_int.PFM_PMU_INTEL_KNM_UNC_CHA31
PFM_PMU_INTEL_KNM_UNC_CHA32 = _perfmon_int.PFM_PMU_INTEL_KNM_UNC_CHA32
PFM_PMU_INTEL_KNM_UNC_CHA33 = _perfmon_int.PFM_PMU_INTEL_KNM_UNC_CHA33
PFM_PMU_INTEL_KNM_UNC_CHA34 = _perfmon_int.PFM_PMU_INTEL_KNM_UNC_CHA34
PFM_PMU_INTEL_KNM_UNC_CHA35 = _perfmon_int.PFM_PMU_INTEL_KNM_UNC_CHA35
PFM_PMU_INTEL_KNM_UNC_CHA36 = _perfmon_int.PFM_PMU_INTEL_KNM_UNC_CHA36
PFM_PMU_INTEL_KNM_UNC_CHA37 = _perfmon_int.PFM_PMU_INTEL_KNM_UNC_CHA37
PFM_PMU_INTEL_KNM_UNC_UBOX = _perfmon_int.PFM_PMU_INTEL_KNM_UNC_UBOX
PFM_PMU_INTEL_KNM_UNC_M2PCIE = _perfmon_int.PFM_PMU_INTEL_KNM_UNC_M2PCIE
PFM_PMU_ARM_THUNDERX2 = _perfmon_int.PFM_PMU_ARM_THUNDERX2
PFM_PMU_INTEL_CLX = _perfmon_int.PFM_PMU_INTEL_CLX
PFM_PMU_ARM_THUNDERX2_DMC0 = _perfmon_int.PFM_PMU_ARM_THUNDERX2_DMC0
PFM_PMU_ARM_THUNDERX2_DMC1 = _perfmon_int.PFM_PMU_ARM_THUNDERX2_DMC1
PFM_PMU_ARM_THUNDERX2_LLC0 = _perfmon_int.PFM_PMU_ARM_THUNDERX2_LLC0
PFM_PMU_ARM_THUNDERX2_LLC1 = _perfmon_int.PFM_PMU_ARM_THUNDERX2_LLC1
PFM_PMU_ARM_THUNDERX2_CCPI0 = _perfmon_int.PFM_PMU_ARM_THUNDERX2_CCPI0
PFM_PMU_ARM_THUNDERX2_CCPI1 = _perfmon_int.PFM_PMU_ARM_THUNDERX2_CCPI1
PFM_PMU_AMD64_FAM17H_ZEN1 = _perfmon_int.PFM_PMU_AMD64_FAM17H_ZEN1
PFM_PMU_AMD64_FAM17H_ZEN2 = _perfmon_int.PFM_PMU_AMD64_FAM17H_ZEN2
PFM_PMU_INTEL_TMT = _perfmon_int.PFM_PMU_INTEL_TMT
PFM_PMU_MAX = _perfmon_int.PFM_PMU_MAX
PFM_PMU_TYPE_UNKNOWN = _perfmon_int.PFM_PMU_TYPE_UNKNOWN
PFM_PMU_TYPE_CORE = _perfmon_int.PFM_PMU_TYPE_CORE
PFM_PMU_TYPE_UNCORE = _perfmon_int.PFM_PMU_TYPE_UNCORE
PFM_PMU_TYPE_OS_GENERIC = _perfmon_int.PFM_PMU_TYPE_OS_GENERIC
PFM_PMU_TYPE_MAX = _perfmon_int.PFM_PMU_TYPE_MAX
PFM_ATTR_NONE = _perfmon_int.PFM_ATTR_NONE
PFM_ATTR_UMASK = _perfmon_int.PFM_ATTR_UMASK
PFM_ATTR_MOD_BOOL = _perfmon_int.PFM_ATTR_MOD_BOOL
PFM_ATTR_MOD_INTEGER = _perfmon_int.PFM_ATTR_MOD_INTEGER
PFM_ATTR_RAW_UMASK = _perfmon_int.PFM_ATTR_RAW_UMASK
PFM_ATTR_MAX = _perfmon_int.PFM_ATTR_MAX
PFM_DTYPE_UNKNOWN = _perfmon_int.PFM_DTYPE_UNKNOWN
PFM_DTYPE_UINT64 = _perfmon_int.PFM_DTYPE_UINT64
PFM_DTYPE_INT64 = _perfmon_int.PFM_DTYPE_INT64
PFM_DTYPE_DOUBLE = _perfmon_int.PFM_DTYPE_DOUBLE
PFM_DTYPE_FIXED = _perfmon_int.PFM_DTYPE_FIXED
PFM_DTYPE_RATIO = _perfmon_int.PFM_DTYPE_RATIO
PFM_DTYPE_CHAR8 = _perfmon_int.PFM_DTYPE_CHAR8
PFM_DTYPE_MAX = _perfmon_int.PFM_DTYPE_MAX
PFM_ATTR_CTRL_UNKNOWN = _perfmon_int.PFM_ATTR_CTRL_UNKNOWN
PFM_ATTR_CTRL_PMU = _perfmon_int.PFM_ATTR_CTRL_PMU
PFM_ATTR_CTRL_PERF_EVENT = _perfmon_int.PFM_ATTR_CTRL_PERF_EVENT
PFM_ATTR_CTRL_MAX = _perfmon_int.PFM_ATTR_CTRL_MAX
PFM_OS_NONE = _perfmon_int.PFM_OS_NONE
PFM_OS_PERF_EVENT = _perfmon_int.PFM_OS_PERF_EVENT
PFM_OS_PERF_EVENT_EXT = _perfmon_int.PFM_OS_PERF_EVENT_EXT
PFM_OS_MAX = _perfmon_int.PFM_OS_MAX
class pfm_pmu_info_t(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _perfmon_int.delete_pfm_pmu_info_t
    name = property(_perfmon_int.pfm_pmu_info_t_name_get, _perfmon_int.pfm_pmu_info_t_name_set)
    desc = property(_perfmon_int.pfm_pmu_info_t_desc_get, _perfmon_int.pfm_pmu_info_t_desc_set)
    size = property(_perfmon_int.pfm_pmu_info_t_size_get, _perfmon_int.pfm_pmu_info_t_size_set)
    pmu = property(_perfmon_int.pfm_pmu_info_t_pmu_get, _perfmon_int.pfm_pmu_info_t_pmu_set)
    type = property(_perfmon_int.pfm_pmu_info_t_type_get, _perfmon_int.pfm_pmu_info_t_type_set)
    nevents = property(_perfmon_int.pfm_pmu_info_t_nevents_get, _perfmon_int.pfm_pmu_info_t_nevents_set)
    first_event = property(_perfmon_int.pfm_pmu_info_t_first_event_get, _perfmon_int.pfm_pmu_info_t_first_event_set)
    max_encoding = property(_perfmon_int.pfm_pmu_info_t_max_encoding_get, _perfmon_int.pfm_pmu_info_t_max_encoding_set)
    num_cntrs = property(_perfmon_int.pfm_pmu_info_t_num_cntrs_get, _perfmon_int.pfm_pmu_info_t_num_cntrs_set)
    num_fixed_cntrs = property(_perfmon_int.pfm_pmu_info_t_num_fixed_cntrs_get, _perfmon_int.pfm_pmu_info_t_num_fixed_cntrs_set)
    flags = property(_perfmon_int.pfm_pmu_info_t_flags_get)

    def __init__(self):
        _perfmon_int.pfm_pmu_info_t_swiginit(self, _perfmon_int.new_pfm_pmu_info_t())

# Register pfm_pmu_info_t in _perfmon_int:
_perfmon_int.pfm_pmu_info_t_swigregister(pfm_pmu_info_t)

class pfm_pmu_info_t_flags(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    is_present = property(_perfmon_int.pfm_pmu_info_t_flags_is_present_get, _perfmon_int.pfm_pmu_info_t_flags_is_present_set)
    is_dfl = property(_perfmon_int.pfm_pmu_info_t_flags_is_dfl_get, _perfmon_int.pfm_pmu_info_t_flags_is_dfl_set)
    reserved_bits = property(_perfmon_int.pfm_pmu_info_t_flags_reserved_bits_get, _perfmon_int.pfm_pmu_info_t_flags_reserved_bits_set)

    def __init__(self):
        _perfmon_int.pfm_pmu_info_t_flags_swiginit(self, _perfmon_int.new_pfm_pmu_info_t_flags())
    __swig_destroy__ = _perfmon_int.delete_pfm_pmu_info_t_flags

# Register pfm_pmu_info_t_flags in _perfmon_int:
_perfmon_int.pfm_pmu_info_t_flags_swigregister(pfm_pmu_info_t_flags)

PFM_EVENT_INFO_SPEC_NA = _perfmon_int.PFM_EVENT_INFO_SPEC_NA
PFM_EVENT_INFO_SPEC_TRUE = _perfmon_int.PFM_EVENT_INFO_SPEC_TRUE
PFM_EVENT_INFO_SPEC_FALSE = _perfmon_int.PFM_EVENT_INFO_SPEC_FALSE
class pfm_event_info_t(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _perfmon_int.delete_pfm_event_info_t
    name = property(_perfmon_int.pfm_event_info_t_name_get, _perfmon_int.pfm_event_info_t_name_set)
    desc = property(_perfmon_int.pfm_event_info_t_desc_get, _perfmon_int.pfm_event_info_t_desc_set)
    equiv = property(_perfmon_int.pfm_event_info_t_equiv_get, _perfmon_int.pfm_event_info_t_equiv_set)
    size = property(_perfmon_int.pfm_event_info_t_size_get, _perfmon_int.pfm_event_info_t_size_set)
    code = property(_perfmon_int.pfm_event_info_t_code_get, _perfmon_int.pfm_event_info_t_code_set)
    pmu = property(_perfmon_int.pfm_event_info_t_pmu_get, _perfmon_int.pfm_event_info_t_pmu_set)
    dtype = property(_perfmon_int.pfm_event_info_t_dtype_get, _perfmon_int.pfm_event_info_t_dtype_set)
    idx = property(_perfmon_int.pfm_event_info_t_idx_get, _perfmon_int.pfm_event_info_t_idx_set)
    nattrs = property(_perfmon_int.pfm_event_info_t_nattrs_get, _perfmon_int.pfm_event_info_t_nattrs_set)
    reserved = property(_perfmon_int.pfm_event_info_t_reserved_get, _perfmon_int.pfm_event_info_t_reserved_set)
    flags = property(_perfmon_int.pfm_event_info_t_flags_get)

    def __init__(self):
        _perfmon_int.pfm_event_info_t_swiginit(self, _perfmon_int.new_pfm_event_info_t())

# Register pfm_event_info_t in _perfmon_int:
_perfmon_int.pfm_event_info_t_swigregister(pfm_event_info_t)

class pfm_event_info_t_flags(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    is_precise = property(_perfmon_int.pfm_event_info_t_flags_is_precise_get, _perfmon_int.pfm_event_info_t_flags_is_precise_set)
    is_speculative = property(_perfmon_int.pfm_event_info_t_flags_is_speculative_get, _perfmon_int.pfm_event_info_t_flags_is_speculative_set)
    reserved_bits = property(_perfmon_int.pfm_event_info_t_flags_reserved_bits_get, _perfmon_int.pfm_event_info_t_flags_reserved_bits_set)

    def __init__(self):
        _perfmon_int.pfm_event_info_t_flags_swiginit(self, _perfmon_int.new_pfm_event_info_t_flags())
    __swig_destroy__ = _perfmon_int.delete_pfm_event_info_t_flags

# Register pfm_event_info_t_flags in _perfmon_int:
_perfmon_int.pfm_event_info_t_flags_swigregister(pfm_event_info_t_flags)

class pfm_event_attr_info_t(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _perfmon_int.delete_pfm_event_attr_info_t
    name = property(_perfmon_int.pfm_event_attr_info_t_name_get, _perfmon_int.pfm_event_attr_info_t_name_set)
    desc = property(_perfmon_int.pfm_event_attr_info_t_desc_get, _perfmon_int.pfm_event_attr_info_t_desc_set)
    equiv = property(_perfmon_int.pfm_event_attr_info_t_equiv_get, _perfmon_int.pfm_event_attr_info_t_equiv_set)
    size = property(_perfmon_int.pfm_event_attr_info_t_size_get, _perfmon_int.pfm_event_attr_info_t_size_set)
    code = property(_perfmon_int.pfm_event_attr_info_t_code_get, _perfmon_int.pfm_event_attr_info_t_code_set)
    type = property(_perfmon_int.pfm_event_attr_info_t_type_get, _perfmon_int.pfm_event_attr_info_t_type_set)
    idx = property(_perfmon_int.pfm_event_attr_info_t_idx_get, _perfmon_int.pfm_event_attr_info_t_idx_set)
    ctrl = property(_perfmon_int.pfm_event_attr_info_t_ctrl_get, _perfmon_int.pfm_event_attr_info_t_ctrl_set)
    flags = property(_perfmon_int.pfm_event_attr_info_t_flags_get)
    defaults = property(_perfmon_int.pfm_event_attr_info_t_defaults_get)

    def __init__(self):
        _perfmon_int.pfm_event_attr_info_t_swiginit(self, _perfmon_int.new_pfm_event_attr_info_t())

# Register pfm_event_attr_info_t in _perfmon_int:
_perfmon_int.pfm_event_attr_info_t_swigregister(pfm_event_attr_info_t)

class pfm_event_attr_info_t_defaults(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    dfl_val64 = property(_perfmon_int.pfm_event_attr_info_t_defaults_dfl_val64_get, _perfmon_int.pfm_event_attr_info_t_defaults_dfl_val64_set)
    dfl_str = property(_perfmon_int.pfm_event_attr_info_t_defaults_dfl_str_get, _perfmon_int.pfm_event_attr_info_t_defaults_dfl_str_set)
    dfl_bool = property(_perfmon_int.pfm_event_attr_info_t_defaults_dfl_bool_get, _perfmon_int.pfm_event_attr_info_t_defaults_dfl_bool_set)
    dfl_int = property(_perfmon_int.pfm_event_attr_info_t_defaults_dfl_int_get, _perfmon_int.pfm_event_attr_info_t_defaults_dfl_int_set)

    def __init__(self):
        _perfmon_int.pfm_event_attr_info_t_defaults_swiginit(self, _perfmon_int.new_pfm_event_attr_info_t_defaults())
    __swig_destroy__ = _perfmon_int.delete_pfm_event_attr_info_t_defaults

# Register pfm_event_attr_info_t_defaults in _perfmon_int:
_perfmon_int.pfm_event_attr_info_t_defaults_swigregister(pfm_event_attr_info_t_defaults)

class pfm_event_attr_info_t_flags(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    is_dfl = property(_perfmon_int.pfm_event_attr_info_t_flags_is_dfl_get, _perfmon_int.pfm_event_attr_info_t_flags_is_dfl_set)
    is_precise = property(_perfmon_int.pfm_event_attr_info_t_flags_is_precise_get, _perfmon_int.pfm_event_attr_info_t_flags_is_precise_set)
    is_speculative = property(_perfmon_int.pfm_event_attr_info_t_flags_is_speculative_get, _perfmon_int.pfm_event_attr_info_t_flags_is_speculative_set)
    reserved_bits = property(_perfmon_int.pfm_event_attr_info_t_flags_reserved_bits_get, _perfmon_int.pfm_event_attr_info_t_flags_reserved_bits_set)

    def __init__(self):
        _perfmon_int.pfm_event_attr_info_t_flags_swiginit(self, _perfmon_int.new_pfm_event_attr_info_t_flags())
    __swig_destroy__ = _perfmon_int.delete_pfm_event_attr_info_t_flags

# Register pfm_event_attr_info_t_flags in _perfmon_int:
_perfmon_int.pfm_event_attr_info_t_flags_swigregister(pfm_event_attr_info_t_flags)

class pfm_pmu_encode_arg_t(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    codes = property(_perfmon_int.pfm_pmu_encode_arg_t_codes_get, _perfmon_int.pfm_pmu_encode_arg_t_codes_set)
    fstr = property(_perfmon_int.pfm_pmu_encode_arg_t_fstr_get, _perfmon_int.pfm_pmu_encode_arg_t_fstr_set)
    size = property(_perfmon_int.pfm_pmu_encode_arg_t_size_get, _perfmon_int.pfm_pmu_encode_arg_t_size_set)
    count = property(_perfmon_int.pfm_pmu_encode_arg_t_count_get, _perfmon_int.pfm_pmu_encode_arg_t_count_set)
    idx = property(_perfmon_int.pfm_pmu_encode_arg_t_idx_get, _perfmon_int.pfm_pmu_encode_arg_t_idx_set)

    def __init__(self):
        _perfmon_int.pfm_pmu_encode_arg_t_swiginit(self, _perfmon_int.new_pfm_pmu_encode_arg_t())
    __swig_destroy__ = _perfmon_int.delete_pfm_pmu_encode_arg_t

# Register pfm_pmu_encode_arg_t in _perfmon_int:
_perfmon_int.pfm_pmu_encode_arg_t_swigregister(pfm_pmu_encode_arg_t)

PFM_PMU_INFO_ABI0 = _perfmon_int.PFM_PMU_INFO_ABI0
PFM_EVENT_INFO_ABI0 = _perfmon_int.PFM_EVENT_INFO_ABI0
PFM_ATTR_INFO_ABI0 = _perfmon_int.PFM_ATTR_INFO_ABI0
PFM_RAW_ENCODE_ABI0 = _perfmon_int.PFM_RAW_ENCODE_ABI0

def pfm_initialize():
    return _perfmon_int.pfm_initialize()

def pfm_terminate():
    return _perfmon_int.pfm_terminate()

def pfm_strerror(code):
    return _perfmon_int.pfm_strerror(code)

def pfm_get_version():
    return _perfmon_int.pfm_get_version()

def pfm_get_pmu_info(pmu):
    return _perfmon_int.pfm_get_pmu_info(pmu)

def pfm_get_event_next(idx):
    return _perfmon_int.pfm_get_event_next(idx)

def pfm_find_event(str):
    return _perfmon_int.pfm_find_event(str)

def pfm_get_event_info(idx, os):
    return _perfmon_int.pfm_get_event_info(idx, os)

def pfm_get_os_event_encoding(str, dfl_plm, os, args):
    return _perfmon_int.pfm_get_os_event_encoding(str, dfl_plm, os, args)

def pfm_get_event_attr_info(eidx, aidx, os):
    return _perfmon_int.pfm_get_event_attr_info(eidx, aidx, os)

def pfm_pmu_validate(pmu_id, fp):
    return _perfmon_int.pfm_pmu_validate(pmu_id, fp)

def pfm_get_event_encoding(str, dfl_plm, fstr, idx, codes, count):
    return _perfmon_int.pfm_get_event_encoding(str, dfl_plm, fstr, idx, codes, count)
PFM_SUCCESS = _perfmon_int.PFM_SUCCESS
PFM_ERR_NOTSUPP = _perfmon_int.PFM_ERR_NOTSUPP
PFM_ERR_INVAL = _perfmon_int.PFM_ERR_INVAL
PFM_ERR_NOINIT = _perfmon_int.PFM_ERR_NOINIT
PFM_ERR_NOTFOUND = _perfmon_int.PFM_ERR_NOTFOUND
PFM_ERR_FEATCOMB = _perfmon_int.PFM_ERR_FEATCOMB
PFM_ERR_UMASK = _perfmon_int.PFM_ERR_UMASK
PFM_ERR_NOMEM = _perfmon_int.PFM_ERR_NOMEM
PFM_ERR_ATTR = _perfmon_int.PFM_ERR_ATTR
PFM_ERR_ATTR_VAL = _perfmon_int.PFM_ERR_ATTR_VAL
PFM_ERR_ATTR_SET = _perfmon_int.PFM_ERR_ATTR_SET
PFM_ERR_TOOMANY = _perfmon_int.PFM_ERR_TOOMANY
PFM_ERR_TOOSMALL = _perfmon_int.PFM_ERR_TOOSMALL

def pfm_get_perf_event_encoding(str, dfl_plm, fstr, idx):
    return _perfmon_int.pfm_get_perf_event_encoding(str, dfl_plm, fstr, idx)


